use std::collections::BTreeMap;
use std::fs::{self, File};
use std::io::{self, BufRead, BufReader, BufWriter, Cursor, Read, Seek, SeekFrom, Write};
use std::path::{Path, PathBuf};

use anyhow::{anyhow, bail, Context, Result};
use clap::{Args, Parser, Subcommand, ValueEnum};
use emote_psb::{
    mdf::{MdfReader, MdfWriter},
    psb::{read::PsbFile, write::PsbWriter},
    value::PsbValue,
    PSB_MDF_SIGNATURE, PSB_SIGNATURE,
};
use serde::{Deserialize, Serialize};

#[derive(Parser, Debug)]
#[command(
    name = "emote-psb",
    version,
    about = "Inspect, dump, pack, unpack, and convert E-mote PSB/MDF files."
)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand, Debug)]
enum Command {
    /// Show high-level file metadata.
    Info {
        input: PathBuf,
        #[arg(long, value_enum, default_value_t = InputFormat::Auto)]
        format: InputFormat,
        /// Emit machine-readable JSON.
        #[arg(long)]
        json: bool,
        #[command(flatten)]
        mdf: MdfCliOptions,
    },

    /// Dump the PSB root object as JSON.
    Dump {
        input: PathBuf,
        #[arg(long, value_enum, default_value_t = InputFormat::Auto)]
        format: InputFormat,
        /// Output JSON path. Prints to stdout when omitted.
        #[arg(short, long)]
        output: Option<PathBuf>,
        /// Pretty-print JSON.
        #[arg(long)]
        pretty: bool,
        #[command(flatten)]
        mdf: MdfCliOptions,
    },

    /// Build a PSB file from a root JSON file and optional resource files.
    Build {
        root_json: PathBuf,
        output: PathBuf,
        /// PSB version. Valid values are 2, 3, and 4.
        #[arg(long, default_value_t = 3)]
        version: u16,
        /// Mark output PSB as encrypted.
        #[arg(long)]
        encrypted: bool,
        /// Add normal resource file. Repeat to preserve indices.
        #[arg(long = "resource", value_name = "FILE")]
        resources: Vec<PathBuf>,
        /// Add extra resource file. Repeat to preserve indices. Requires version 4.
        #[arg(long = "extra", value_name = "FILE")]
        extras: Vec<PathBuf>,
    },

    /// Repack a PSB/MDF into a normalized PSB while preserving root and resources.
    Repack {
        input: PathBuf,
        output: PathBuf,
        #[arg(long, value_enum, default_value_t = InputFormat::Auto)]
        format: InputFormat,
        /// Override output PSB version. Defaults to source version.
        #[arg(long)]
        version: Option<u16>,
        /// Override output encrypted flag.
        #[arg(long, value_name = "BOOL")]
        encrypted: Option<bool>,
        #[command(flatten)]
        mdf: MdfCliOptions,
    },

    /// Unpack PSB/MDF into root JSON, resources, extra resources, and manifest JSON.
    Unpack {
        input: PathBuf,
        out_dir: PathBuf,
        #[arg(long, value_enum, default_value_t = InputFormat::Auto)]
        format: InputFormat,
        /// Overwrite an existing non-empty output directory.
        #[arg(long)]
        overwrite: bool,
        /// Pretty-print generated root.json and manifest.json.
        #[arg(long)]
        pretty: bool,
        #[command(flatten)]
        mdf: MdfCliOptions,
    },

    /// Pack a PSB from a manifest JSON generated by `unpack`.
    Pack {
        manifest_json: PathBuf,
        output: PathBuf,
        /// Override manifest root JSON path.
        #[arg(long)]
        root: Option<PathBuf>,
        /// Override manifest resources. Repeat to preserve indices.
        #[arg(long = "resource", value_name = "FILE")]
        resources: Vec<PathBuf>,
        /// Override manifest extra resources. Repeat to preserve indices. Requires version 4.
        #[arg(long = "extra", value_name = "FILE")]
        extras: Vec<PathBuf>,
        /// Override manifest version.
        #[arg(long)]
        version: Option<u16>,
        /// Override manifest encrypted flag.
        #[arg(long, value_name = "BOOL")]
        encrypted: Option<bool>,
    },

    /// Decode an MDF wrapper to raw PSB bytes.
    DecodeMdf {
        input: PathBuf,
        output: PathBuf,
        #[command(flatten)]
        mdf: MdfCliOptions,
    },

    /// Encode raw PSB bytes into an MDF wrapper.
    EncodeMdf {
        input: PathBuf,
        output: PathBuf,
        /// zlib compression level passed to MdfWriter.
        #[arg(long, default_value_t = 6)]
        level: u32,
    },

    /// Convert PSB <-> MDF. With `auto`, the target format is inferred from output extension.
    Convert {
        input: PathBuf,
        output: PathBuf,
        #[arg(long = "from", value_enum, default_value_t = InputFormat::Auto)]
        from_format: InputFormat,
        #[arg(long = "to", value_enum, default_value_t = OutputFormat::Auto)]
        to_format: OutputFormat,
        /// zlib compression level used when writing MDF.
        #[arg(long, default_value_t = 6)]
        level: u32,
        #[command(flatten)]
        mdf: MdfCliOptions,
    },

    /// Inspect an MArchive pair: `{archive}_info.psb.m` plus `{archive}_body.bin`.
    ArchiveInfo {
        /// Archive info PSB/MDF file, for example scenario_info.psb.m.
        info: PathBuf,
        /// Archive body file, for example scenario_body.bin.
        body: PathBuf,
        /// Output JSON report path. Prints to stdout when omitted.
        #[arg(short, long)]
        output: Option<PathBuf>,
        /// Pretty-print JSON.
        #[arg(long)]
        pretty: bool,
        /// Decode each MDF body slice and validate the decoded PSB signature.
        #[arg(long)]
        deep: bool,
        #[command(flatten)]
        mdf: MdfCliOptions,
    },

    /// Extract all slices from an MArchive body using the decoded info manifest.
    ArchiveUnpack {
        /// Archive info PSB/MDF file, for example scenario_info.psb.m.
        info: PathBuf,
        /// Archive body file, for example scenario_body.bin.
        body: PathBuf,
        /// Output directory.
        out_dir: PathBuf,
        /// Overwrite an existing non-empty output directory.
        #[arg(long)]
        overwrite: bool,
        /// Pretty-print generated JSON files.
        #[arg(long)]
        pretty: bool,
        /// Also write the original body slices before MDF decoding.
        #[arg(long)]
        raw_slices: bool,
        /// Abort on the first entry-level extraction error.
        #[arg(long)]
        strict: bool,
        #[command(flatten)]
        mdf: MdfCliOptions,
    },
}

#[derive(Clone, Debug, ValueEnum)]
enum InputFormat {
    Auto,
    Psb,
    Mdf,
}

#[derive(Clone, Debug, ValueEnum)]
enum OutputFormat {
    Auto,
    Psb,
    Mdf,
}

#[derive(Clone, Debug, Default, Args)]
struct MdfCliOptions {
    /// Full MT19937 MDF seed, usually key + original file name.
    #[arg(long = "mdf-seed", value_name = "SEED")]
    seed: Option<String>,

    /// MT19937 MDF game key. The CLI combines it with --mdf-name or the input file name.
    #[arg(long = "mdf-key", value_name = "KEY")]
    key: Option<String>,

    /// Original MDF file name used for seed derivation. Defaults to the input file name.
    #[arg(long = "mdf-name", value_name = "NAME")]
    name: Option<String>,

    /// MT19937 MDF key length. FreeMote commonly uses 131 / 0x83.
    #[arg(long = "mdf-key-len", default_value_t = 0x83)]
    key_len: usize,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
enum FileKind {
    Psb,
    Mdf,
}

#[derive(Debug, Serialize)]
struct InfoReport {
    path: PathBuf,
    input_kind: FileKind,
    version: u16,
    encrypted: bool,
    checksum: Option<u32>,
    names: TableReport,
    strings: TableReport,
    resources: ResourceReport,
    extra_resources: ResourceReport,
}

#[derive(Debug, Serialize)]
struct TableReport {
    entries: usize,
    bytes: usize,
}

#[derive(Debug, Serialize)]
struct ResourceReport {
    count: usize,
    sizes: Vec<usize>,
}

#[derive(Debug, Serialize, Deserialize)]
struct PackageManifest {
    version: u16,
    encrypted: bool,
    checksum: Option<u32>,
    root: PathBuf,
    resources: Vec<PathBuf>,
    extra_resources: Vec<PathBuf>,
}

#[derive(Debug, Serialize, Deserialize)]
struct ArchiveInfoRoot {
    id: Option<String>,
    #[serde(default)]
    expire_suffix_list: Vec<String>,
    file_info: BTreeMap<String, Vec<u64>>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
enum ArchiveSliceKind {
    Mdf,
    Psb,
    Psz,
    Raw,
}

#[derive(Debug, Clone)]
struct ArchiveEntry {
    index: usize,
    name: String,
    offset: u64,
    length: u64,
    seed_name: String,
}

#[derive(Debug, Serialize)]
struct ArchiveReport {
    info: PathBuf,
    body: PathBuf,
    suffix: String,
    body_size: u64,
    entry_count: usize,
    entries: Vec<ArchiveEntryReport>,
    errors: Vec<String>,
}

#[derive(Debug, Serialize)]
struct ArchiveEntryReport {
    index: usize,
    name: String,
    seed_name: String,
    offset: u64,
    length: u64,
    kind: ArchiveSliceKind,
    mdf_original_size: Option<u32>,
    decoded_size: Option<usize>,
    psb_signature_ok: Option<bool>,
    output: Option<PathBuf>,
    raw_output: Option<PathBuf>,
    error: Option<String>,
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Command::Info {
            input,
            format,
            json,
            mdf,
        } => info_command(input, format, json, mdf),
        Command::Dump {
            input,
            format,
            output,
            pretty,
            mdf,
        } => dump_command(input, format, output, pretty, mdf),
        Command::Build {
            root_json,
            output,
            version,
            encrypted,
            resources,
            extras,
        } => build_command(root_json, output, version, encrypted, resources, extras),
        Command::Repack {
            input,
            output,
            format,
            version,
            encrypted,
            mdf,
        } => repack_command(input, output, format, version, encrypted, mdf),
        Command::Unpack {
            input,
            out_dir,
            format,
            overwrite,
            pretty,
            mdf,
        } => unpack_command(input, out_dir, format, overwrite, pretty, mdf),
        Command::Pack {
            manifest_json,
            output,
            root,
            resources,
            extras,
            version,
            encrypted,
        } => pack_command(
            manifest_json,
            output,
            root,
            resources,
            extras,
            version,
            encrypted,
        ),
        Command::DecodeMdf { input, output, mdf } => decode_mdf_command(input, output, mdf),
        Command::EncodeMdf {
            input,
            output,
            level,
        } => encode_mdf_command(input, output, level),
        Command::Convert {
            input,
            output,
            from_format,
            to_format,
            level,
            mdf,
        } => convert_command(input, output, from_format, to_format, level, mdf),
        Command::ArchiveInfo {
            info,
            body,
            output,
            pretty,
            deep,
            mdf,
        } => archive_info_command(info, body, output, pretty, deep, mdf),
        Command::ArchiveUnpack {
            info,
            body,
            out_dir,
            overwrite,
            pretty,
            raw_slices,
            strict,
            mdf,
        } => archive_unpack_command(info, body, out_dir, overwrite, pretty, raw_slices, strict, mdf),
    }
}

fn info_command(input: PathBuf, format: InputFormat, json: bool, mdf: MdfCliOptions) -> Result<()> {
    let kind = resolve_input_kind(&input, format)?;
    let mut psb = open_as_psb_file(&input, kind, &mdf)?;

    let version = psb.version;
    let encrypted = psb.encrypted;
    let checksum = psb.checksum;
    let names_entries = psb.names.iter().count();
    let names_bytes = psb.names.len();
    let strings_entries = psb.strings.iter().count();
    let strings_bytes = psb.strings.len();
    let resource_count = psb.resources();
    let resource_sizes = read_all_normal_resource_sizes(&mut psb)?;
    let extra_resource_count = psb.extra_resources();
    let extra_resource_sizes = read_all_extra_resource_sizes(&mut psb)?;

    let report = InfoReport {
        path: input,
        input_kind: kind,
        version,
        encrypted,
        checksum,
        names: TableReport {
            entries: names_entries,
            bytes: names_bytes,
        },
        strings: TableReport {
            entries: strings_entries,
            bytes: strings_bytes,
        },
        resources: ResourceReport {
            count: resource_count,
            sizes: resource_sizes,
        },
        extra_resources: ResourceReport {
            count: extra_resource_count,
            sizes: extra_resource_sizes,
        },
    };

    if json {
        write_json_stdout(&report, true)?;
    } else {
        println!("path: {}", report.path.display());
        println!("container: {:?}", report.input_kind);
        println!("version: {}", report.version);
        println!("encrypted: {}", report.encrypted);
        println!("checksum: {:?}", report.checksum);
        println!(
            "names: {} entries, {} bytes",
            report.names.entries, report.names.bytes
        );
        println!(
            "strings: {} entries, {} bytes",
            report.strings.entries, report.strings.bytes
        );
        println!("resources: {}", report.resources.count);
        for (idx, size) in report.resources.sizes.iter().enumerate() {
            println!("  resource[{idx}]: {size} bytes");
        }
        println!("extra_resources: {}", report.extra_resources.count);
        for (idx, size) in report.extra_resources.sizes.iter().enumerate() {
            println!("  extra[{idx}]: {size} bytes");
        }
    }

    Ok(())
}

fn dump_command(
    input: PathBuf,
    format: InputFormat,
    output: Option<PathBuf>,
    pretty: bool,
    mdf: MdfCliOptions,
) -> Result<()> {
    let kind = resolve_input_kind(&input, format)?;
    let mut psb = open_as_psb_file(&input, kind, &mdf)?;
    let root = psb
        .deserialize_root::<PsbValue>()
        .context("failed to deserialize PSB root")?;
    write_json_output(&root, output.as_deref(), pretty)
}

fn build_command(
    root_json: PathBuf,
    output: PathBuf,
    version: u16,
    encrypted: bool,
    resources: Vec<PathBuf>,
    extras: Vec<PathBuf>,
) -> Result<()> {
    let version = validate_version(version)?;
    let root = read_root_json(&root_json)?;
    let resource_blobs = read_blobs(&resources)?;
    let extra_blobs = read_blobs(&extras)?;
    write_psb_file(&output, version, encrypted, &root, &resource_blobs, &extra_blobs)
}

fn repack_command(
    input: PathBuf,
    output: PathBuf,
    format: InputFormat,
    version: Option<u16>,
    encrypted: Option<bool>,
    mdf: MdfCliOptions,
) -> Result<()> {
    let kind = resolve_input_kind(&input, format)?;
    let mut psb = open_as_psb_file(&input, kind, &mdf)?;
    let root = psb
        .deserialize_root::<PsbValue>()
        .context("failed to deserialize PSB root")?;
    let resource_blobs = read_all_normal_resources(&mut psb)?;
    let extra_blobs = read_all_extra_resources(&mut psb)?;
    let out_version = validate_version(version.unwrap_or(psb.version))?;
    let out_encrypted = encrypted.unwrap_or(psb.encrypted);
    write_psb_file(
        &output,
        out_version,
        out_encrypted,
        &root,
        &resource_blobs,
        &extra_blobs,
    )
}

fn unpack_command(
    input: PathBuf,
    out_dir: PathBuf,
    format: InputFormat,
    overwrite: bool,
    pretty: bool,
    mdf: MdfCliOptions,
) -> Result<()> {
    let kind = resolve_input_kind(&input, format)?;
    prepare_output_dir(&out_dir, overwrite)?;

    let mut psb = open_as_psb_file(&input, kind, &mdf)?;
    let root = psb
        .deserialize_root::<PsbValue>()
        .context("failed to deserialize PSB root")?;

    let root_file = PathBuf::from("root.json");
    write_json_output(&root, Some(&out_dir.join(&root_file)), pretty)?;

    let resource_blobs = read_all_normal_resources(&mut psb)?;
    let mut resource_files = Vec::with_capacity(resource_blobs.len());
    for (idx, bytes) in resource_blobs.iter().enumerate() {
        let name = PathBuf::from(format!("resource_{idx:04}.bin"));
        fs::write(out_dir.join(&name), bytes)
            .with_context(|| format!("failed to write {}", name.display()))?;
        resource_files.push(name);
    }

    let extra_blobs = read_all_extra_resources(&mut psb)?;
    let mut extra_files = Vec::with_capacity(extra_blobs.len());
    for (idx, bytes) in extra_blobs.iter().enumerate() {
        let name = PathBuf::from(format!("extra_{idx:04}.bin"));
        fs::write(out_dir.join(&name), bytes)
            .with_context(|| format!("failed to write {}", name.display()))?;
        extra_files.push(name);
    }

    let manifest = PackageManifest {
        version: psb.version,
        encrypted: psb.encrypted,
        checksum: psb.checksum,
        root: root_file,
        resources: resource_files,
        extra_resources: extra_files,
    };
    write_json_output(&manifest, Some(&out_dir.join("manifest.json")), pretty)
}

fn pack_command(
    manifest_json: PathBuf,
    output: PathBuf,
    root_override: Option<PathBuf>,
    resource_overrides: Vec<PathBuf>,
    extra_overrides: Vec<PathBuf>,
    version_override: Option<u16>,
    encrypted_override: Option<bool>,
) -> Result<()> {
    let manifest: PackageManifest = read_json_file(&manifest_json)?;
    let manifest_dir = manifest_json
        .parent()
        .map(Path::to_path_buf)
        .unwrap_or_else(|| PathBuf::from("."));

    let root_path = root_override.unwrap_or_else(|| manifest_dir.join(manifest.root));
    let resource_paths = if resource_overrides.is_empty() {
        manifest
            .resources
            .iter()
            .map(|p| manifest_dir.join(p))
            .collect::<Vec<_>>()
    } else {
        resource_overrides
    };
    let extra_paths = if extra_overrides.is_empty() {
        manifest
            .extra_resources
            .iter()
            .map(|p| manifest_dir.join(p))
            .collect::<Vec<_>>()
    } else {
        extra_overrides
    };

    let root = read_root_json(&root_path)?;
    let resources = read_blobs(&resource_paths)?;
    let extras = read_blobs(&extra_paths)?;
    let version = validate_version(version_override.unwrap_or(manifest.version))?;
    let encrypted = encrypted_override.unwrap_or(manifest.encrypted);

    write_psb_file(&output, version, encrypted, &root, &resources, &extras)
}

fn decode_mdf_command(input: PathBuf, output: PathBuf, mdf: MdfCliOptions) -> Result<()> {
    let decoded = decode_mdf_to_vec(&input, &mdf)?;
    fs::write(&output, decoded).with_context(|| format!("failed to write {}", output.display()))
}

fn encode_mdf_command(input: PathBuf, output: PathBuf, level: u32) -> Result<()> {
    let psb_bytes = fs::read(&input).with_context(|| format!("failed to read {}", input.display()))?;
    ensure_psb_signature(&psb_bytes).with_context(|| format!("{} is not a PSB file", input.display()))?;
    write_mdf_file(&output, &psb_bytes, level)
}

fn convert_command(
    input: PathBuf,
    output: PathBuf,
    from_format: InputFormat,
    to_format: OutputFormat,
    level: u32,
    mdf: MdfCliOptions,
) -> Result<()> {
    let source_kind = resolve_input_kind(&input, from_format)?;
    let target_kind = resolve_output_kind(&output, to_format)?;

    match (source_kind, target_kind) {
        (FileKind::Psb, FileKind::Psb) | (FileKind::Mdf, FileKind::Mdf) => {
            fs::copy(&input, &output).with_context(|| {
                format!("failed to copy {} to {}", input.display(), output.display())
            })?;
            Ok(())
        }
        (FileKind::Mdf, FileKind::Psb) => decode_mdf_command(input, output, mdf),
        (FileKind::Psb, FileKind::Mdf) => encode_mdf_command(input, output, level),
    }
}


fn archive_info_command(
    info: PathBuf,
    body: PathBuf,
    output: Option<PathBuf>,
    pretty: bool,
    deep: bool,
    mdf: MdfCliOptions,
) -> Result<()> {
    if deep {
        require_mdf_key(&mdf)?;
    }
    let report = build_archive_report(&info, &body, &mdf, deep, None, false, false)?;
    write_json_output(&report, output.as_deref(), pretty)
}

fn archive_unpack_command(
    info: PathBuf,
    body: PathBuf,
    out_dir: PathBuf,
    overwrite: bool,
    pretty: bool,
    raw_slices: bool,
    strict: bool,
    mdf: MdfCliOptions,
) -> Result<()> {
    require_mdf_key(&mdf)?;
    prepare_output_dir(&out_dir, overwrite)?;

    let (_archive_root, root_value) = read_archive_root(&info, &mdf)?;
    write_json_output(&root_value, Some(&out_dir.join("info_root.json")), pretty)?;

    let report = build_archive_report(&info, &body, &mdf, true, Some(&out_dir), raw_slices, strict)?;
    write_json_output(&report, Some(&out_dir.join("manifest.json")), pretty)
}

fn read_archive_root(info_path: &Path, mdf: &MdfCliOptions) -> Result<(ArchiveInfoRoot, PsbValue)> {
    let info_kind = detect_file_kind(info_path)?;
    let mut psb = open_as_psb_file(info_path, info_kind, mdf)
        .with_context(|| format!("failed to read archive info {}", info_path.display()))?;
    let root_value = psb
        .deserialize_root::<PsbValue>()
        .context("failed to deserialize archive info PSB root")?;
    let archive_root: ArchiveInfoRoot = serde_json::from_value(
        serde_json::to_value(&root_value).context("failed to convert archive info root to JSON")?,
    )
    .context("archive info root does not match expected MArchive schema")?;
    if archive_root.id.as_deref() != Some("archive") {
        bail!(
            "archive info root id is {:?}, expected \"archive\"",
            archive_root.id
        );
    }
    Ok((archive_root, root_value))
}

fn build_archive_report(
    info_path: &Path,
    body_path: &Path,
    mdf: &MdfCliOptions,
    deep: bool,
    extract_dir: Option<&Path>,
    raw_slices: bool,
    strict: bool,
) -> Result<ArchiveReport> {
    let (archive_root, _) = read_archive_root(info_path, mdf)?;
    let suffix = archive_root
        .expire_suffix_list
        .first()
        .cloned()
        .unwrap_or_default();
    let entries = archive_entries(&archive_root, &suffix)?;
    let body_size = body_path
        .metadata()
        .with_context(|| format!("failed to stat {}", body_path.display()))?
        .len();

    if let Some(dir) = extract_dir {
        fs::create_dir_all(dir.join("entries"))
            .with_context(|| format!("failed to create {}", dir.join("entries").display()))?;
        if raw_slices {
            fs::create_dir_all(dir.join("raw_slices"))
                .with_context(|| format!("failed to create {}", dir.join("raw_slices").display()))?;
        }
    }

    let mut reports = Vec::with_capacity(entries.len());
    let mut errors = Vec::new();
    let mut expected_offset = 0u64;

    for entry in entries {
        if entry.offset != expected_offset {
            errors.push(format!(
                "gap_or_overlap before {}: expected offset {}, got {}",
                entry.name, expected_offset, entry.offset
            ));
        }
        if entry.offset.saturating_add(entry.length) > body_size {
            errors.push(format!(
                "{} extends beyond body: offset {} + length {} > {}",
                entry.name, entry.offset, entry.length, body_size
            ));
        }

        let mut report = ArchiveEntryReport {
            index: entry.index,
            name: entry.name.clone(),
            seed_name: entry.seed_name.clone(),
            offset: entry.offset,
            length: entry.length,
            kind: ArchiveSliceKind::Raw,
            mdf_original_size: None,
            decoded_size: None,
            psb_signature_ok: None,
            output: None,
            raw_output: None,
            error: None,
        };

        let result = process_archive_entry(body_path, &entry, mdf, deep, extract_dir, raw_slices, &mut report);
        if let Err(err) = result {
            let message = err.to_string();
            if strict {
                return Err(err).with_context(|| format!("failed to process archive entry {}", entry.name));
            }
            errors.push(format!("{}: {}", entry.name, message));
            report.error = Some(message);
        }

        expected_offset = entry.offset.saturating_add(entry.length);
        reports.push(report);
    }

    if expected_offset != body_size {
        errors.push(format!(
            "body tail mismatch: last entry ends at {}, body size is {}",
            expected_offset, body_size
        ));
    }

    Ok(ArchiveReport {
        info: info_path.to_path_buf(),
        body: body_path.to_path_buf(),
        suffix,
        body_size,
        entry_count: reports.len(),
        entries: reports,
        errors,
    })
}

fn archive_entries(root: &ArchiveInfoRoot, suffix: &str) -> Result<Vec<ArchiveEntry>> {
    let mut entries = Vec::with_capacity(root.file_info.len());
    for (name, pair) in &root.file_info {
        if pair.len() < 2 {
            bail!("file_info entry {} has {} values, expected at least 2", name, pair.len());
        }
        entries.push(ArchiveEntry {
            index: 0,
            name: name.clone(),
            offset: pair[0],
            length: pair[1],
            seed_name: archive_entry_seed_name(name, suffix),
        });
    }
    entries.sort_by_key(|entry| entry.offset);
    for (idx, entry) in entries.iter_mut().enumerate() {
        entry.index = idx;
    }
    Ok(entries)
}

fn process_archive_entry(
    body_path: &Path,
    entry: &ArchiveEntry,
    mdf: &MdfCliOptions,
    deep: bool,
    extract_dir: Option<&Path>,
    raw_slices: bool,
    report: &mut ArchiveEntryReport,
) -> Result<()> {
    let slice = read_body_slice(body_path, entry.offset, entry.length)?;
    report.kind = detect_slice_kind(&slice);
    report.mdf_original_size = mdf_original_size(&slice);

    if let Some(dir) = extract_dir {
        if raw_slices {
            let raw_rel = PathBuf::from("raw_slices").join(format!(
                "{idx:04}_{name}.slice",
                idx = entry.index,
                name = sanitize_file_name(&entry.name)
            ));
            fs::write(dir.join(&raw_rel), &slice)
                .with_context(|| format!("failed to write {}", dir.join(&raw_rel).display()))?;
            report.raw_output = Some(raw_rel);
        }
    }

    let decoded = match report.kind {
        ArchiveSliceKind::Mdf if deep || extract_dir.is_some() => {
            let decoded = decode_mdf_slice_to_vec(&slice, &entry.seed_name, mdf)?;
            report.decoded_size = Some(decoded.len());
            report.psb_signature_ok = Some(has_psb_signature(&decoded));
            Some(decoded)
        }
        ArchiveSliceKind::Psb if extract_dir.is_some() => {
            report.decoded_size = Some(slice.len());
            report.psb_signature_ok = Some(true);
            Some(slice)
        }
        ArchiveSliceKind::Psb => {
            report.decoded_size = Some(slice.len());
            report.psb_signature_ok = Some(true);
            None
        }
        _ => None,
    };

    if let (Some(dir), Some(bytes)) = (extract_dir, decoded) {
        let ext = if has_psb_signature(&bytes) { "psb" } else { "bin" };
        let rel = PathBuf::from("entries").join(format!(
            "{idx:04}_{name}.{ext}",
            idx = entry.index,
            name = sanitize_file_name(&entry.name),
            ext = ext
        ));
        fs::write(dir.join(&rel), bytes)
            .with_context(|| format!("failed to write {}", dir.join(&rel).display()))?;
        report.output = Some(rel);
    }

    Ok(())
}

fn read_body_slice(path: &Path, offset: u64, length: u64) -> Result<Vec<u8>> {
    let length_usize = usize::try_from(length).context("body slice length does not fit in usize")?;
    let mut file = File::open(path).with_context(|| format!("failed to open {}", path.display()))?;
    file.seek(SeekFrom::Start(offset))
        .with_context(|| format!("failed to seek {} to {}", path.display(), offset))?;
    let mut buf = vec![0u8; length_usize];
    file.read_exact(&mut buf)
        .with_context(|| format!("failed to read {} bytes at offset {}", length, offset))?;
    Ok(buf)
}

fn decode_mdf_slice_to_vec(slice: &[u8], seed_name: &str, mdf: &MdfCliOptions) -> Result<Vec<u8>> {
    let key = require_mdf_key(mdf)?;
    let reader = BufReader::new(Cursor::new(slice.to_vec()));
    let mut mdf_reader = MdfReader::open_with_key(reader, key, seed_name, mdf.key_len)
        .with_context(|| format!("failed to open MDF slice with seed name {}", seed_name))?;
    let mut decoded = Vec::new();
    mdf_reader
        .read_to_end(&mut decoded)
        .with_context(|| format!("failed to decompress MDF slice with seed name {}", seed_name))?;
    Ok(decoded)
}

fn archive_entry_seed_name(name: &str, suffix: &str) -> String {
    if name.to_ascii_lowercase().ends_with(".m") {
        name.to_string()
    } else {
        format!("{name}{suffix}")
    }
}

fn detect_slice_kind(slice: &[u8]) -> ArchiveSliceKind {
    if slice.starts_with(b"mdf\0") {
        ArchiveSliceKind::Mdf
    } else if slice.starts_with(b"PSB\0") {
        ArchiveSliceKind::Psb
    } else if slice.starts_with(b"PSZ\0") {
        ArchiveSliceKind::Psz
    } else {
        ArchiveSliceKind::Raw
    }
}

fn mdf_original_size(slice: &[u8]) -> Option<u32> {
    if slice.len() >= 8 && slice.starts_with(b"mdf\0") {
        Some(u32::from_le_bytes(slice[4..8].try_into().ok()?))
    } else {
        None
    }
}

fn has_psb_signature(bytes: &[u8]) -> bool {
    bytes.len() >= 4 && u32::from_le_bytes(bytes[0..4].try_into().expect("slice length checked")) == PSB_SIGNATURE
}

fn sanitize_file_name(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for ch in name.chars() {
        let bad = matches!(ch, '/' | '\\' | ':' | '*' | '?' | '"' | '<' | '>' | '|') || ch.is_control();
        if bad {
            out.push('_');
        } else {
            out.push(ch);
        }
    }
    if out.is_empty() {
        "entry".to_string()
    } else {
        out
    }
}

fn require_mdf_key(mdf: &MdfCliOptions) -> Result<&str> {
    mdf.key
        .as_deref()
        .ok_or_else(|| anyhow!("archive body MDF slices require --mdf-key"))
}

fn open_as_psb_file(path: &Path, kind: FileKind, mdf: &MdfCliOptions) -> Result<PsbFile<BufReader<Cursor<Vec<u8>>>>> {
    let psb_bytes = match kind {
        FileKind::Psb => fs::read(path).with_context(|| format!("failed to read {}", path.display()))?,
        FileKind::Mdf => decode_mdf_to_vec(path, mdf)?,
    };
    ensure_psb_signature(&psb_bytes).with_context(|| format!("{} did not decode to PSB", path.display()))?;
    let cursor = Cursor::new(psb_bytes);
    PsbFile::open(BufReader::new(cursor)).context("failed to open PSB")
}

fn open_mdf_reader<R>(reader: R, path: &Path, options: &MdfCliOptions) -> std::result::Result<MdfReader, emote_psb::mdf::error::MdfOpenError>
where
    R: BufRead,
{
    if let Some(seed) = &options.seed {
        return MdfReader::open_with_seed(reader, seed.as_bytes(), options.key_len);
    }

    if let Some(key) = &options.key {
        let file_name = options
            .name
            .as_deref()
            .or_else(|| path.file_name().and_then(|name| name.to_str()))
            .unwrap_or_default();
        return MdfReader::open_with_key(reader, key.as_str(), file_name, options.key_len);
    }

    MdfReader::open(reader)
}

fn decode_mdf_to_vec(path: &Path, mdf_options: &MdfCliOptions) -> Result<Vec<u8>> {
    let file = File::open(path).with_context(|| format!("failed to open {}", path.display()))?;
    let reader = BufReader::new(file);
    let mut mdf = open_mdf_reader(reader, path, mdf_options).context("failed to open MDF")?;
    let mut decoded = Vec::new();
    mdf.read_to_end(&mut decoded)
        .context("failed to decompress MDF")?;
    ensure_psb_signature(&decoded)?;
    Ok(decoded)
}

fn write_psb_file(
    output: &Path,
    version: u16,
    encrypted: bool,
    root: &PsbValue,
    resources: &[Vec<u8>],
    extras: &[Vec<u8>],
) -> Result<()> {
    if !extras.is_empty() && version <= 3 {
        bail!("extra resources require PSB version 4; got version {version}");
    }

    let file = File::create(output).with_context(|| format!("failed to create {}", output.display()))?;
    let stream = BufWriter::new(file);
    let mut writer = PsbWriter::new(version, encrypted, root, stream)
        .context("failed to initialize PSB writer")?;

    for (idx, bytes) in resources.iter().enumerate() {
        writer
            .add_resource(Cursor::new(bytes.clone()))
            .with_context(|| format!("failed to add resource {idx}"))?;
    }
    for (idx, bytes) in extras.iter().enumerate() {
        writer
            .add_extra(Cursor::new(bytes.clone()))
            .with_context(|| format!("failed to add extra resource {idx}"))?;
    }

    writer.finish().context("failed to write PSB")?;
    Ok(())
}

fn write_mdf_file(output: &Path, psb_bytes: &[u8], level: u32) -> Result<()> {
    let level = validate_compression_level(level)?;
    let file = File::create(output).with_context(|| format!("failed to create {}", output.display()))?;
    let stream = BufWriter::new(file);
    let mut writer = MdfWriter::new(stream, level).context("failed to initialize MDF writer")?;
    writer.write_all(psb_bytes).context("failed to write MDF")?;
    let mut stream = writer.finish().context("failed to finish MDF")?;
    stream.flush().context("failed to flush MDF output")?;
    Ok(())
}

fn read_all_normal_resource_sizes<S>(psb: &mut PsbFile<S>) -> Result<Vec<usize>>
where
    S: BufRead + Read + Seek,
{
    Ok(read_all_normal_resources(psb)?
        .into_iter()
        .map(|bytes| bytes.len())
        .collect())
}

fn read_all_extra_resource_sizes<S>(psb: &mut PsbFile<S>) -> Result<Vec<usize>>
where
    S: BufRead + Read + Seek,
{
    Ok(read_all_extra_resources(psb)?
        .into_iter()
        .map(|bytes| bytes.len())
        .collect())
}

fn read_all_normal_resources<S>(psb: &mut PsbFile<S>) -> Result<Vec<Vec<u8>>>
where
    S: BufRead + Read + Seek,
{
    let count = psb.resources();
    let mut out = Vec::with_capacity(count);
    for idx in 0..count {
        let mut resource = psb
            .open_resource(idx)
            .with_context(|| format!("failed to open resource {idx}"))?
            .ok_or_else(|| anyhow!("resource {idx} is out of range"))?;
        let mut bytes = Vec::new();
        resource
            .read_to_end(&mut bytes)
            .with_context(|| format!("failed to read resource {idx}"))?;
        out.push(bytes);
    }
    Ok(out)
}

fn read_all_extra_resources<S>(psb: &mut PsbFile<S>) -> Result<Vec<Vec<u8>>>
where
    S: BufRead + Read + Seek,
{
    let count = psb.extra_resources();
    let mut out = Vec::with_capacity(count);
    for idx in 0..count {
        let mut resource = psb
            .open_extra_resource(idx)
            .with_context(|| format!("failed to open extra resource {idx}"))?
            .ok_or_else(|| anyhow!("extra resource {idx} is out of range"))?;
        let mut bytes = Vec::new();
        resource
            .read_to_end(&mut bytes)
            .with_context(|| format!("failed to read extra resource {idx}"))?;
        out.push(bytes);
    }
    Ok(out)
}

fn read_root_json(path: &Path) -> Result<PsbValue> {
    read_json_file(path).with_context(|| format!("failed to read root JSON {}", path.display()))
}

fn read_json_file<T>(path: &Path) -> Result<T>
where
    T: for<'de> Deserialize<'de>,
{
    let file = File::open(path).with_context(|| format!("failed to open {}", path.display()))?;
    serde_json::from_reader(BufReader::new(file)).context("failed to parse JSON")
}

fn read_blobs(paths: &[PathBuf]) -> Result<Vec<Vec<u8>>> {
    paths
        .iter()
        .map(|path| fs::read(path).with_context(|| format!("failed to read {}", path.display())))
        .collect()
}

fn prepare_output_dir(path: &Path, overwrite: bool) -> Result<()> {
    if path.exists() {
        if !path.is_dir() {
            bail!("{} exists and is not a directory", path.display());
        }
        if overwrite {
            fs::remove_dir_all(path)
                .with_context(|| format!("failed to clear {}", path.display()))?;
            fs::create_dir_all(path)
                .with_context(|| format!("failed to recreate {}", path.display()))?;
        } else if path.read_dir()?.next().is_some() {
            bail!(
                "{} is not empty; pass --overwrite to replace it",
                path.display()
            );
        }
    } else {
        fs::create_dir_all(path)
            .with_context(|| format!("failed to create {}", path.display()))?;
    }
    Ok(())
}

fn write_json_output<T>(value: &T, output: Option<&Path>, pretty: bool) -> Result<()>
where
    T: Serialize,
{
    match output {
        Some(path) => {
            let file = File::create(path)
                .with_context(|| format!("failed to create {}", path.display()))?;
            let mut writer = BufWriter::new(file);
            if pretty {
                serde_json::to_writer_pretty(&mut writer, value).context("failed to write JSON")?;
            } else {
                serde_json::to_writer(&mut writer, value).context("failed to write JSON")?;
            }
            writer.write_all(b"\n")?;
            writer.flush()?;
        }
        None => write_json_stdout(value, pretty)?,
    }
    Ok(())
}

fn write_json_stdout<T>(value: &T, pretty: bool) -> Result<()>
where
    T: Serialize,
{
    let stdout = io::stdout();
    let mut lock = stdout.lock();
    if pretty {
        serde_json::to_writer_pretty(&mut lock, value).context("failed to write JSON")?;
    } else {
        serde_json::to_writer(&mut lock, value).context("failed to write JSON")?;
    }
    lock.write_all(b"\n")?;
    lock.flush()?;
    Ok(())
}

fn validate_compression_level(level: u32) -> Result<u8> {
    if level <= 9 {
        Ok(level as u8)
    } else {
        bail!("invalid MDF compression level {level}; valid values are 0 through 9")
    }
}

fn validate_version(version: u16) -> Result<u16> {
    match version {
        2 | 3 | 4 => Ok(version),
        _ => bail!("unsupported PSB version {version}; valid values are 2, 3, and 4"),
    }
}

fn resolve_input_kind(path: &Path, requested: InputFormat) -> Result<FileKind> {
    match requested {
        InputFormat::Psb => Ok(FileKind::Psb),
        InputFormat::Mdf => Ok(FileKind::Mdf),
        InputFormat::Auto => detect_file_kind(path),
    }
}

fn resolve_output_kind(path: &Path, requested: OutputFormat) -> Result<FileKind> {
    match requested {
        OutputFormat::Psb => Ok(FileKind::Psb),
        OutputFormat::Mdf => Ok(FileKind::Mdf),
        OutputFormat::Auto => match path
            .extension()
            .and_then(|ext| ext.to_str())
            .map(|ext| ext.to_ascii_lowercase())
            .as_deref()
        {
            Some("mdf") => Ok(FileKind::Mdf),
            Some("psb") | Some("scn") => Ok(FileKind::Psb),
            _ => Err(anyhow!(
                "cannot infer output format from {}; pass --to psb or --to mdf",
                path.display()
            )),
        },
    }
}

fn detect_file_kind(path: &Path) -> Result<FileKind> {
    let mut file = File::open(path).with_context(|| format!("failed to open {}", path.display()))?;
    let mut sig = [0u8; 4];
    file.read_exact(&mut sig)
        .with_context(|| format!("failed to read signature from {}", path.display()))?;
    let sig = u32::from_le_bytes(sig);
    match sig {
        PSB_SIGNATURE => Ok(FileKind::Psb),
        PSB_MDF_SIGNATURE => Ok(FileKind::Mdf),
        _ => bail!(
            "{} is neither PSB nor MDF; pass --format explicitly only if you know it is valid",
            path.display()
        ),
    }
}

fn ensure_psb_signature(bytes: &[u8]) -> Result<()> {
    if bytes.len() < 4 {
        bail!("buffer is too small to contain a PSB signature");
    }
    let sig = u32::from_le_bytes(bytes[0..4].try_into().expect("slice length checked"));
    if sig == PSB_SIGNATURE {
        Ok(())
    } else {
        bail!("invalid PSB signature 0x{sig:08x}")
    }
}
