use std::collections::BTreeMap;
use std::fs::{self, File};
use std::io::{self, BufRead, BufReader, BufWriter, Cursor, Read, Seek, SeekFrom, Write};
use std::path::{Path, PathBuf};

use anyhow::{anyhow, bail, Context, Result};
use byteorder::{LittleEndian, WriteBytesExt};
use clap::{ArgAction, Args, Parser, Subcommand, ValueEnum};
use emote_psb::{
    mdf::{MdfReader, MdfShell, MdfWriter},
    psb::{read::PsbFile, write::PsbWriter},
    value::PsbValue,
    PSB_MDF_SIGNATURE, PSB_SIGNATURE,
};
use flate2::{write::ZlibEncoder, Compression};
use serde::{Deserialize, Serialize};

#[derive(Parser, Debug)]
#[command(
    name = "emote-psb",
    version,
    about = "Inspect, dump, pack, unpack, convert, and repack E-mote PSB/MDF files."
)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand, Debug)]
enum Command {
    /// Show high-level file metadata.
    Info {
        input: PathBuf,

        #[arg(long, value_enum, default_value_t = InputFormat::Auto)]
        format: InputFormat,

        /// Emit machine-readable JSON.
        #[arg(long)]
        json: bool,

        #[command(flatten)]
        mdf: MdfCliOptions,
    },

    /// Dump the PSB root object as JSON.
    Dump {
        input: PathBuf,

        #[arg(long, value_enum, default_value_t = InputFormat::Auto)]
        format: InputFormat,

        /// Output JSON path. Prints to stdout when omitted.
        #[arg(short, long)]
        output: Option<PathBuf>,

        /// Pretty-print JSON.
        #[arg(long)]
        pretty: bool,

        #[command(flatten)]
        mdf: MdfCliOptions,
    },

    /// Build a PSB file from a root JSON file and optional resource files.
    Build {
        root_json: PathBuf,
        output: PathBuf,

        /// PSB version. Valid values are 2, 3, and 4.
        #[arg(long, default_value_t = 3)]
        version: u16,

        /// Mark output PSB as encrypted.
        #[arg(long)]
        encrypted: bool,

        /// Add normal resource file. Repeat to preserve indices.
        #[arg(long = "resource", value_name = "FILE")]
        resources: Vec<PathBuf>,

        /// Add extra resource file. Repeat to preserve indices. Requires version 4.
        #[arg(long = "extra", value_name = "FILE")]
        extras: Vec<PathBuf>,
    },

    /// Repack a PSB/MDF into a normalized PSB while preserving root and resources.
    Repack {
        input: PathBuf,
        output: PathBuf,

        #[arg(long, value_enum, default_value_t = InputFormat::Auto)]
        format: InputFormat,

        /// Override output PSB version. Defaults to source version.
        #[arg(long)]
        version: Option<u16>,

        /// Override output encrypted flag.
        #[arg(long, value_name = "BOOL")]
        encrypted: Option<bool>,

        #[command(flatten)]
        mdf: MdfCliOptions,
    },

    /// Unpack PSB/MDF into root JSON, resources, extra resources, and manifest JSON.
    Unpack {
        input: PathBuf,
        out_dir: PathBuf,

        #[arg(long, value_enum, default_value_t = InputFormat::Auto)]
        format: InputFormat,

        /// Overwrite an existing non-empty output directory.
        #[arg(long)]
        overwrite: bool,

        /// Pretty-print generated root.json and manifest.json.
        #[arg(long)]
        pretty: bool,

        #[command(flatten)]
        mdf: MdfCliOptions,
    },

    /// Pack a PSB from a manifest JSON generated by `unpack`.
    Pack {
        manifest_json: PathBuf,
        output: PathBuf,

        /// Override manifest root JSON path.
        #[arg(long)]
        root: Option<PathBuf>,

        /// Override manifest resources. Repeat to preserve indices.
        #[arg(long = "resource", value_name = "FILE")]
        resources: Vec<PathBuf>,

        /// Override manifest extra resources. Repeat to preserve indices. Requires version 4.
        #[arg(long = "extra", value_name = "FILE")]
        extras: Vec<PathBuf>,

        /// Override manifest version.
        #[arg(long)]
        version: Option<u16>,

        /// Override manifest encrypted flag.
        #[arg(long, value_name = "BOOL")]
        encrypted: Option<bool>,
    },

    /// Decode an MDF wrapper to raw PSB bytes.
    DecodeMdf {
        input: PathBuf,
        output: PathBuf,

        #[command(flatten)]
        mdf: MdfCliOptions,
    },

    /// Encode raw PSB bytes into an MDF wrapper.
    EncodeMdf {
        input: PathBuf,
        output: PathBuf,

        /// zlib compression level passed to MdfWriter.
        #[arg(long, default_value_t = 6)]
        level: u32,
    },

    /// Convert PSB <-> MDF. With `auto`, the target format is inferred from output extension.
    Convert {
        input: PathBuf,
        output: PathBuf,

        #[arg(long = "from", value_enum, default_value_t = InputFormat::Auto)]
        from_format: InputFormat,

        #[arg(long = "to", value_enum, default_value_t = OutputFormat::Auto)]
        to_format: OutputFormat,

        /// zlib compression level used when writing MDF.
        #[arg(long, default_value_t = 6)]
        level: u32,

        #[command(flatten)]
        mdf: MdfCliOptions,
    },

    /// Inspect an MArchive pair. Pass the `*_info.psb.m`; the matching `*_body.bin` is inferred.
    ArchiveInfo {
        /// Archive info PSB/MDF file, for example scenario_info.psb.m.
        info: PathBuf,

        /// Archive body file. Defaults to `{prefix}_body.bin` next to `{prefix}_info.psb.m`.
        #[arg(long)]
        body: Option<PathBuf>,

        /// Output JSON report path. Prints to stdout when omitted.
        #[arg(short, long)]
        output: Option<PathBuf>,

        /// Pretty-print JSON.
        #[arg(long)]
        pretty: bool,

        /// Decode each MDF body slice and validate the decoded PSB signature.
        #[arg(long)]
        deep: bool,

        #[command(flatten)]
        mdf: MdfCliOptions,
    },

    /// Extract all slices from an MArchive using the decoded info manifest.
    ArchiveUnpack {
        /// Archive info PSB/MDF file, for example scenario_info.psb.m. The body defaults to scenario_body.bin in the same directory.
        info: PathBuf,

        /// Output directory. By default, writes editable files directly under this directory using original archive names.
        out_dir: PathBuf,

        /// Archive body file. Defaults to `{prefix}_body.bin` next to `{prefix}_info.psb.m`.
        #[arg(long)]
        body: Option<PathBuf>,

        /// Overwrite an existing non-empty output directory.
        #[arg(long)]
        overwrite: bool,

        /// Pretty-print generated JSON files.
        #[arg(long)]
        pretty: bool,

        /// Also write the original body slices before MDF decoding.
        #[arg(long)]
        raw_slices: bool,

        /// Compatibility no-op: named entries are now written by default.
        #[arg(long, hide = true, action = ArgAction::SetTrue)]
        named_entries: bool,

        /// Also write legacy numbered decoded entries, for example entries/0038_startup.bin. Disabled by default.
        #[arg(long = "indexed-entries")]
        indexed_entries: bool,

        /// Abort on the first entry-level extraction error.
        #[arg(long)]
        strict: bool,

        #[command(flatten)]
        mdf: MdfCliOptions,
    },

    /// Repack an MArchive pair after editing files extracted by `archive-unpack`.
    RepackArchive {
        /// Original archive info PSB/MDF file, for example scenario_info.psb.m. The original body defaults to scenario_body.bin in the same directory.
        info: PathBuf,

        /// Directory produced by `archive-unpack`, or a FreeMote-like source directory.
        in_dir: PathBuf,

        /// Output archive info PSB/MDF file. The output body defaults to the matching `*_body.bin` next to this path.
        out_info: PathBuf,

        /// Original archive body file. Defaults to `{prefix}_body.bin` next to the input info file.
        #[arg(long)]
        body: Option<PathBuf>,

        /// Output archive body file. Defaults to `{prefix}_body.bin` next to the output info file.
        #[arg(long = "out-body")]
        out_body: Option<PathBuf>,

        /// Output format for out_info. Auto treats `.psb.m`, `.m`, and `.mdf` as MDF.
        #[arg(long = "info-format", value_enum, default_value_t = OutputFormat::Auto)]
        info_format: OutputFormat,

        /// zlib compression level used for rewritten MDF body slices and MDF info output.
        #[arg(long, default_value_t = 6)]
        level: u32,

        /// Output shell for rewritten MDF body slices.
        #[arg(long = "body-mdf-shell", value_enum, default_value_t = MdfWriteShell::Auto)]
        body_mdf_shell: MdfWriteShell,

        /// Output shell for out_info when it is MDF.
        #[arg(long = "info-mdf-shell", value_enum, default_value_t = MdfWriteShell::Auto)]
        info_mdf_shell: MdfWriteShell,

        /// MT19937 seed variant used when writing MT19937 MDF.
        #[arg(long = "mt-seed-variant", value_enum, default_value_t = MtSeedVariantCli::Md5ArrayLe)]
        mt_seed_variant: MtSeedVariantCli,

        /// MT19937 XOR key variant used when writing MT19937 MDF.
        #[arg(long = "mt-key-variant", value_enum, default_value_t = MtKeyVariantCli::CyclicLeWords)]
        mt_key_variant: MtKeyVariantCli,

        /// Preserve original raw body slice when no replacement is found.
        #[arg(long, default_value_t = true)]
        preserve_missing: bool,

        /// Abort if an entry has no replacement in in_dir.
        #[arg(long)]
        strict: bool,

        /// Prefer raw_slices/*.slice over decoded entries/*.psb or entries/*.bin.
        #[arg(long)]
        prefer_raw_slices: bool,

        /// Preserve source offset order. Use `--free-mote-order` to sort by archive name.
        #[arg(long = "free-mote-order")]
        free_mote_order: bool,

        /// Override the output MDF seed name for out_info. Defaults to out_info file name.
        #[arg(long = "info-mdf-name")]
        info_mdf_name: Option<String>,

        #[command(flatten)]
        mdf: MdfCliOptions,
    },
}

#[derive(Clone, Copy, Debug, ValueEnum)]
enum InputFormat {
    Auto,
    Psb,
    Mdf,
}

#[derive(Clone, Copy, Debug, ValueEnum)]
enum OutputFormat {
    Auto,
    Psb,
    Mdf,
}

#[derive(Clone, Copy, Debug, ValueEnum)]
enum MdfWriteShell {
    Auto,
    Plain,
    Mt19937,
}

#[derive(Clone, Copy, Debug, ValueEnum)]
enum MtSeedVariantCli {
    Md5ArrayLe,
    Md5ArrayBe,
    Md5FirstLe,
    Md5FirstBe,
}

#[derive(Clone, Copy, Debug, ValueEnum)]
enum MtKeyVariantCli {
    CyclicLeWords,
    CyclicBeWords,
    StreamLeWords,
    StreamBeWords,
}

#[derive(Clone, Debug, Default, Args)]
struct MdfCliOptions {
    /// Full MT19937 MDF seed, usually key + original file name.
    #[arg(long = "mdf-seed", value_name = "SEED")]
    seed: Option<String>,

    /// MT19937 MDF game key. The CLI combines it with --mdf-name or the input file name.
    #[arg(long = "mdf-key", value_name = "KEY")]
    key: Option<String>,

    /// Original MDF file name used for seed derivation. Defaults to the input file name.
    #[arg(long = "mdf-name", value_name = "NAME")]
    name: Option<String>,

    /// MT19937 MDF key length. FreeMote commonly uses 131 / 0x83.
    #[arg(long = "mdf-key-len", default_value_t = 0x83)]
    key_len: usize,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
enum FileKind {
    Psb,
    Mdf,
}

#[derive(Debug, Serialize)]
struct InfoReport {
    path: PathBuf,
    input_kind: FileKind,
    version: u16,
    encrypted: bool,
    checksum: Option<u32>,
    names: TableReport,
    strings: TableReport,
    resources: ResourceReport,
    extra_resources: ResourceReport,
}

#[derive(Debug, Serialize)]
struct TableReport {
    entries: usize,
    bytes: usize,
}

#[derive(Debug, Serialize)]
struct ResourceReport {
    count: usize,
    sizes: Vec<usize>,
}

#[derive(Debug, Serialize, Deserialize)]
struct PackageManifest {
    version: u16,
    encrypted: bool,
    checksum: Option<u32>,
    root: PathBuf,
    resources: Vec<PathBuf>,
    extra_resources: Vec<PathBuf>,
}

#[derive(Debug, Serialize, Deserialize)]
struct ArchiveInfoRoot {
    id: Option<String>,

    #[serde(default)]
    expire_suffix_list: Vec<String>,

    file_info: BTreeMap<String, Vec<u64>>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
enum ArchiveSliceKind {
    Mdf,
    Psb,
    Psz,
    Raw,
}

#[derive(Debug, Clone)]
struct ArchiveEntry {
    index: usize,
    name: String,
    offset: u64,
    length: u64,
    seed_name: String,
}

#[derive(Debug, Serialize)]
struct ArchiveReport {
    info: PathBuf,
    body: PathBuf,
    suffix: String,
    body_size: u64,
    entry_count: usize,
    entries: Vec<ArchiveEntryReport>,
    errors: Vec<String>,
}

#[derive(Debug, Serialize)]
struct ArchiveEntryReport {
    index: usize,
    name: String,
    seed_name: String,
    offset: u64,
    length: u64,
    kind: ArchiveSliceKind,
    mdf_original_size: Option<u32>,
    decoded_size: Option<usize>,
    psb_signature_ok: Option<bool>,
    output: Option<PathBuf>,
    named_output: Option<PathBuf>,
    raw_output: Option<PathBuf>,
    error: Option<String>,
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Command::Info {
            input,
            format,
            json,
            mdf,
        } => info_command(input, format, json, mdf),
        Command::Dump {
            input,
            format,
            output,
            pretty,
            mdf,
        } => dump_command(input, format, output, pretty, mdf),
        Command::Build {
            root_json,
            output,
            version,
            encrypted,
            resources,
            extras,
        } => build_command(root_json, output, version, encrypted, resources, extras),
        Command::Repack {
            input,
            output,
            format,
            version,
            encrypted,
            mdf,
        } => repack_command(input, output, format, version, encrypted, mdf),
        Command::Unpack {
            input,
            out_dir,
            format,
            overwrite,
            pretty,
            mdf,
        } => unpack_command(input, out_dir, format, overwrite, pretty, mdf),
        Command::Pack {
            manifest_json,
            output,
            root,
            resources,
            extras,
            version,
            encrypted,
        } => pack_command(
            manifest_json,
            output,
            root,
            resources,
            extras,
            version,
            encrypted,
        ),
        Command::DecodeMdf { input, output, mdf } => decode_mdf_command(input, output, mdf),
        Command::EncodeMdf {
            input,
            output,
            level,
        } => encode_mdf_command(input, output, level),
        Command::Convert {
            input,
            output,
            from_format,
            to_format,
            level,
            mdf,
        } => convert_command(input, output, from_format, to_format, level, mdf),
        Command::ArchiveInfo {
            info,
            body,
            output,
            pretty,
            deep,
            mdf,
        } => archive_info_command(info, body, output, pretty, deep, mdf),
        Command::ArchiveUnpack {
            info,
            out_dir,
            body,
            overwrite,
            pretty,
            raw_slices,
            named_entries: _named_entries_compat,
            indexed_entries,
            strict,
            mdf,
        } => archive_unpack_command(
            info,
            body,
            out_dir,
            overwrite,
            pretty,
            raw_slices,
            true,
            indexed_entries,
            strict,
            mdf,
        ),
        Command::RepackArchive {
            info,
            in_dir,
            out_info,
            body,
            out_body,
            info_format,
            level,
            body_mdf_shell,
            info_mdf_shell,
            mt_seed_variant,
            mt_key_variant,
            preserve_missing,
            strict,
            prefer_raw_slices,
            free_mote_order,
            info_mdf_name,
            mdf,
        } => repack_archive_command(
            info,
            body,
            in_dir,
            out_info,
            out_body,
            info_format,
            level,
            body_mdf_shell,
            info_mdf_shell,
            mt_seed_variant,
            mt_key_variant,
            preserve_missing,
            strict,
            prefer_raw_slices,
            free_mote_order,
            info_mdf_name,
            mdf,
        ),
    }
}

fn info_command(input: PathBuf, format: InputFormat, json: bool, mdf: MdfCliOptions) -> Result<()> {
    let kind = resolve_input_kind(&input, format)?;
    let mut psb = open_as_psb_file(&input, kind, &mdf)?;

    let version = psb.version;
    let encrypted = psb.encrypted;
    let checksum = psb.checksum;
    let names_entries = psb.names.iter().count();
    let names_bytes = psb.names.len();
    let strings_entries = psb.strings.iter().count();
    let strings_bytes = psb.strings.len();
    let resource_count = psb.resources();
    let resource_sizes = read_all_normal_resource_sizes(&mut psb)?;
    let extra_resource_count = psb.extra_resources();
    let extra_resource_sizes = read_all_extra_resource_sizes(&mut psb)?;

    let report = InfoReport {
        path: input,
        input_kind: kind,
        version,
        encrypted,
        checksum,
        names: TableReport {
            entries: names_entries,
            bytes: names_bytes,
        },
        strings: TableReport {
            entries: strings_entries,
            bytes: strings_bytes,
        },
        resources: ResourceReport {
            count: resource_count,
            sizes: resource_sizes,
        },
        extra_resources: ResourceReport {
            count: extra_resource_count,
            sizes: extra_resource_sizes,
        },
    };

    if json {
        write_json_stdout(&report, true)?;
    } else {
        println!("path: {}", report.path.display());
        println!("container: {:?}", report.input_kind);
        println!("version: {}", report.version);
        println!("encrypted: {}", report.encrypted);
        println!("checksum: {:?}", report.checksum);
        println!(
            "names: {} entries, {} bytes",
            report.names.entries, report.names.bytes
        );
        println!(
            "strings: {} entries, {} bytes",
            report.strings.entries, report.strings.bytes
        );
        println!("resources: {}", report.resources.count);
        for (idx, size) in report.resources.sizes.iter().enumerate() {
            println!("  resource[{idx}]: {size} bytes");
        }
        println!("extra_resources: {}", report.extra_resources.count);
        for (idx, size) in report.extra_resources.sizes.iter().enumerate() {
            println!("  extra[{idx}]: {size} bytes");
        }
    }

    Ok(())
}

fn dump_command(
    input: PathBuf,
    format: InputFormat,
    output: Option<PathBuf>,
    pretty: bool,
    mdf: MdfCliOptions,
) -> Result<()> {
    let kind = resolve_input_kind(&input, format)?;
    let mut psb = open_as_psb_file(&input, kind, &mdf)?;
    let root = psb
        .deserialize_root::<PsbValue>()
        .context("failed to deserialize PSB root")?;
    write_json_output(&root, output.as_deref(), pretty)
}

fn build_command(
    root_json: PathBuf,
    output: PathBuf,
    version: u16,
    encrypted: bool,
    resources: Vec<PathBuf>,
    extras: Vec<PathBuf>,
) -> Result<()> {
    let version = validate_version(version)?;
    let root = read_root_json(&root_json)?;
    let resource_blobs = read_blobs(&resources)?;
    let extra_blobs = read_blobs(&extras)?;
    write_psb_file(&output, version, encrypted, &root, &resource_blobs, &extra_blobs)
}

fn repack_command(
    input: PathBuf,
    output: PathBuf,
    format: InputFormat,
    version: Option<u16>,
    encrypted: Option<bool>,
    mdf: MdfCliOptions,
) -> Result<()> {
    let kind = resolve_input_kind(&input, format)?;
    let mut psb = open_as_psb_file(&input, kind, &mdf)?;
    let root = psb
        .deserialize_root::<PsbValue>()
        .context("failed to deserialize PSB root")?;
    let resource_blobs = read_all_normal_resources(&mut psb)?;
    let extra_blobs = read_all_extra_resources(&mut psb)?;
    let out_version = validate_version(version.unwrap_or(psb.version))?;
    let out_encrypted = encrypted.unwrap_or(psb.encrypted);
    write_psb_file(
        &output,
        out_version,
        out_encrypted,
        &root,
        &resource_blobs,
        &extra_blobs,
    )
}

fn unpack_command(
    input: PathBuf,
    out_dir: PathBuf,
    format: InputFormat,
    overwrite: bool,
    pretty: bool,
    mdf: MdfCliOptions,
) -> Result<()> {
    let kind = resolve_input_kind(&input, format)?;
    prepare_output_dir(&out_dir, overwrite)?;

    let mut psb = open_as_psb_file(&input, kind, &mdf)?;
    let root = psb
        .deserialize_root::<PsbValue>()
        .context("failed to deserialize PSB root")?;

    let root_file = PathBuf::from("root.json");
    write_json_output(&root, Some(&out_dir.join(&root_file)), pretty)?;

    let resource_blobs = read_all_normal_resources(&mut psb)?;
    let mut resource_files = Vec::with_capacity(resource_blobs.len());
    for (idx, bytes) in resource_blobs.iter().enumerate() {
        let name = PathBuf::from(format!("resource_{idx:04}.bin"));
        fs::write(out_dir.join(&name), bytes)
            .with_context(|| format!("failed to write {}", name.display()))?;
        resource_files.push(name);
    }

    let extra_blobs = read_all_extra_resources(&mut psb)?;
    let mut extra_files = Vec::with_capacity(extra_blobs.len());
    for (idx, bytes) in extra_blobs.iter().enumerate() {
        let name = PathBuf::from(format!("extra_{idx:04}.bin"));
        fs::write(out_dir.join(&name), bytes)
            .with_context(|| format!("failed to write {}", name.display()))?;
        extra_files.push(name);
    }

    let manifest = PackageManifest {
        version: psb.version,
        encrypted: psb.encrypted,
        checksum: psb.checksum,
        root: root_file,
        resources: resource_files,
        extra_resources: extra_files,
    };

    write_json_output(&manifest, Some(&out_dir.join("manifest.json")), pretty)
}

fn pack_command(
    manifest_json: PathBuf,
    output: PathBuf,
    root_override: Option<PathBuf>,
    resource_overrides: Vec<PathBuf>,
    extra_overrides: Vec<PathBuf>,
    version_override: Option<u16>,
    encrypted_override: Option<bool>,
) -> Result<()> {
    let manifest: PackageManifest = read_json_file(&manifest_json)?;
    let manifest_dir = manifest_json
        .parent()
        .map(Path::to_path_buf)
        .unwrap_or_else(|| PathBuf::from("."));

    let root_path = root_override.unwrap_or_else(|| manifest_dir.join(manifest.root));
    let resource_paths = if resource_overrides.is_empty() {
        manifest
            .resources
            .iter()
            .map(|p| manifest_dir.join(p))
            .collect::<Vec<_>>()
    } else {
        resource_overrides
    };
    let extra_paths = if extra_overrides.is_empty() {
        manifest
            .extra_resources
            .iter()
            .map(|p| manifest_dir.join(p))
            .collect::<Vec<_>>()
    } else {
        extra_overrides
    };

    let root = read_root_json(&root_path)?;
    let resources = read_blobs(&resource_paths)?;
    let extras = read_blobs(&extra_paths)?;
    let version = validate_version(version_override.unwrap_or(manifest.version))?;
    let encrypted = encrypted_override.unwrap_or(manifest.encrypted);
    write_psb_file(&output, version, encrypted, &root, &resources, &extras)
}

fn decode_mdf_command(input: PathBuf, output: PathBuf, mdf: MdfCliOptions) -> Result<()> {
    let decoded = decode_mdf_to_vec(&input, &mdf)?;
    fs::write(&output, decoded).with_context(|| format!("failed to write {}", output.display()))
}

fn encode_mdf_command(input: PathBuf, output: PathBuf, level: u32) -> Result<()> {
    let psb_bytes = fs::read(&input).with_context(|| format!("failed to read {}", input.display()))?;
    ensure_psb_signature(&psb_bytes).with_context(|| format!("{} is not a PSB file", input.display()))?;
    write_mdf_file(&output, &psb_bytes, level)
}

fn convert_command(
    input: PathBuf,
    output: PathBuf,
    from_format: InputFormat,
    to_format: OutputFormat,
    level: u32,
    mdf: MdfCliOptions,
) -> Result<()> {
    let source_kind = resolve_input_kind(&input, from_format)?;
    let target_kind = resolve_output_kind(&output, to_format)?;

    match (source_kind, target_kind) {
        (FileKind::Psb, FileKind::Psb) | (FileKind::Mdf, FileKind::Mdf) => {
            fs::copy(&input, &output).with_context(|| {
                format!("failed to copy {} to {}", input.display(), output.display())
            })?;
            Ok(())
        }
        (FileKind::Mdf, FileKind::Psb) => decode_mdf_command(input, output, mdf),
        (FileKind::Psb, FileKind::Mdf) => encode_mdf_command(input, output, level),
    }
}

fn archive_info_command(
    info: PathBuf,
    body: Option<PathBuf>,
    output: Option<PathBuf>,
    pretty: bool,
    deep: bool,
    mdf: MdfCliOptions,
) -> Result<()> {
    if deep {
        require_mdf_key(&mdf)?;
    }
    let body = resolve_archive_body_input_path(body.as_deref(), &info)?;
    let report = build_archive_report(&info, &body, &mdf, deep, None, false, false, false, false)?;
    write_json_output(&report, output.as_deref(), pretty)
}

fn archive_unpack_command(
    info: PathBuf,
    body: Option<PathBuf>,
    out_dir: PathBuf,
    overwrite: bool,
    pretty: bool,
    raw_slices: bool,
    named_entries: bool,
    indexed_entries: bool,
    strict: bool,
    mdf: MdfCliOptions,
) -> Result<()> {
    require_mdf_key(&mdf)?;
    let body = resolve_archive_body_input_path(body.as_deref(), &info)?;
    prepare_output_dir(&out_dir, overwrite)?;

    let metadata_dir = out_dir.join(".emote_archive");
    fs::create_dir_all(&metadata_dir)
        .with_context(|| format!("failed to create {}", metadata_dir.display()))?;

    let (_archive_root, root_value) = read_archive_root(&info, &mdf)?;
    write_json_output(&root_value, Some(&metadata_dir.join("info_root.json")), pretty)?;

    let report = build_archive_report(
        &info,
        &body,
        &mdf,
        true,
        Some(&out_dir),
        raw_slices,
        named_entries,
        indexed_entries,
        strict,
    )?;
    write_json_output(&report, Some(&metadata_dir.join("manifest.json")), pretty)
}

#[allow(clippy::too_many_arguments)]
fn repack_archive_command(
    info: PathBuf,
    body: Option<PathBuf>,
    in_dir: PathBuf,
    out_info: PathBuf,
    out_body: Option<PathBuf>,
    info_format: OutputFormat,
    level: u32,
    body_mdf_shell: MdfWriteShell,
    info_mdf_shell: MdfWriteShell,
    mt_seed_variant: MtSeedVariantCli,
    mt_key_variant: MtKeyVariantCli,
    preserve_missing: bool,
    strict: bool,
    prefer_raw_slices: bool,
    free_mote_order: bool,
    info_mdf_name: Option<String>,
    mdf: MdfCliOptions,
) -> Result<()> {
    let level = validate_compression_level(level)?;
    let body = resolve_archive_body_input_path(body.as_deref(), &info)?;
    let out_body = resolve_archive_body_output_path(out_body.as_deref(), &out_info)?;
    let info_kind = detect_file_kind(&info)?;
    let source_info_shell = if info_kind == FileKind::Mdf {
        Some(decode_mdf_to_vec_with_shell(&info, &mdf)?.1)
    } else {
        None
    };

    let mut info_psb = open_as_psb_file(&info, info_kind, &mdf)
        .with_context(|| format!("failed to read archive info {}", info.display()))?;
    let info_version = info_psb.version;
    let info_encrypted = info_psb.encrypted;
    let root_value = info_psb
        .deserialize_root::<PsbValue>()
        .context("failed to deserialize archive info PSB root")?;

    let archive_root: ArchiveInfoRoot = serde_json::from_value(
        serde_json::to_value(&root_value).context("failed to convert archive root to JSON")?,
    )
    .context("archive info root does not match expected MArchive schema")?;

    if archive_root.id.as_deref() != Some("archive") {
        bail!(
            "archive info root id is {:?}, expected \"archive\"",
            archive_root.id
        );
    }

    let suffix = archive_root
        .expire_suffix_list
        .first()
        .cloned()
        .unwrap_or_default();
    let mut entries = archive_entries(&archive_root, &suffix)?;
    if free_mote_order {
        entries.sort_by(|a, b| a.name.cmp(&b.name));
        for (idx, entry) in entries.iter_mut().enumerate() {
            entry.index = idx;
        }
    }

    let mut body_out = BufWriter::new(
        File::create(&out_body).with_context(|| format!("failed to create {}", out_body.display()))?,
    );
    let mut new_file_info: BTreeMap<String, Vec<u64>> = BTreeMap::new();
    let mut offset = 0u64;

    for entry in &entries {
        let original_slice = read_body_slice(&body, entry.offset, entry.length)
            .with_context(|| format!("failed to read original slice {}", entry.name))?;
        let original_kind = detect_slice_kind(&original_slice);
        let replacement = find_archive_replacement(&in_dir, entry, prefer_raw_slices);

        let packed = match replacement {
            Some(path) => pack_archive_replacement(
                &path,
                &original_slice,
                original_kind,
                entry,
                &mdf,
                level,
                body_mdf_shell,
                mt_seed_variant,
                mt_key_variant,
            )
            .with_context(|| format!("failed to pack replacement for {}", entry.name))?,
            None if strict || !preserve_missing => {
                bail!("missing replacement for archive entry {}", entry.name);
            }
            None => original_slice,
        };

        body_out
            .write_all(&packed)
            .with_context(|| format!("failed to write body slice {}", entry.name))?;

        let length = u64::try_from(packed.len()).context("body slice length does not fit in u64")?;
        new_file_info.insert(entry.name.clone(), vec![offset, length]);
        offset = offset
            .checked_add(length)
            .ok_or_else(|| anyhow!("archive body offset overflow"))?;
    }

    body_out.flush().context("failed to flush output body")?;

    let mut new_root_json =
        serde_json::to_value(&root_value).context("failed to convert archive root to JSON")?;
    let file_info = new_root_json
        .get_mut("file_info")
        .ok_or_else(|| anyhow!("archive root has no file_info field"))?;
    *file_info = serde_json::to_value(&new_file_info).context("failed to rebuild file_info")?;

    let new_root: PsbValue = serde_json::from_value(new_root_json)
        .context("failed to convert rebuilt archive root to PsbValue")?;

    write_archive_info_output(
        &out_info,
        info_format,
        info_version,
        info_encrypted,
        &new_root,
        level,
        &mdf,
        source_info_shell,
        info_mdf_shell,
        mt_seed_variant,
        mt_key_variant,
        info_mdf_name.as_deref(),
    )
}


fn resolve_archive_body_input_path(explicit: Option<&Path>, info: &Path) -> Result<PathBuf> {
    let body = match explicit {
        Some(path) => path.to_path_buf(),
        None => archive_body_path_from_info_path(info)?,
    };

    if !body.is_file() {
        bail!(
            "archive body file {} was not found; pass --body explicitly if it is not next to the info file",
            body.display()
        );
    }

    Ok(body)
}

fn resolve_archive_body_output_path(explicit: Option<&Path>, out_info: &Path) -> Result<PathBuf> {
    match explicit {
        Some(path) => Ok(path.to_path_buf()),
        None => archive_body_path_from_info_path(out_info),
    }
}

fn archive_body_path_from_info_path(info: &Path) -> Result<PathBuf> {
    let file_name = info
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| anyhow!("cannot infer archive body path from {}", info.display()))?;

    let body_name = file_name
        .strip_suffix("_info.psb.m")
        .or_else(|| file_name.strip_suffix("_info.mdf"))
        .or_else(|| file_name.strip_suffix("_info.psb"))
        .or_else(|| file_name.strip_suffix("_info.m"))
        .map(|prefix| format!("{prefix}_body.bin"))
        .ok_or_else(|| {
            anyhow!(
                "cannot infer archive body path from {}; expected a file name ending with _info.psb.m, _info.mdf, _info.psb, or _info.m",
                info.display()
            )
        })?;

    Ok(info
        .parent()
        .map(|parent| parent.join(&body_name))
        .unwrap_or_else(|| PathBuf::from(body_name)))
}

fn read_archive_root(info_path: &Path, mdf: &MdfCliOptions) -> Result<(ArchiveInfoRoot, PsbValue)> {
    let info_kind = detect_file_kind(info_path)?;
    let mut psb = open_as_psb_file(info_path, info_kind, mdf)
        .with_context(|| format!("failed to read archive info {}", info_path.display()))?;
    let root_value = psb
        .deserialize_root::<PsbValue>()
        .context("failed to deserialize archive info PSB root")?;
    let archive_root: ArchiveInfoRoot = serde_json::from_value(
        serde_json::to_value(&root_value).context("failed to convert archive info root to JSON")?,
    )
    .context("archive info root does not match expected MArchive schema")?;

    if archive_root.id.as_deref() != Some("archive") {
        bail!(
            "archive info root id is {:?}, expected \"archive\"",
            archive_root.id
        );
    }

    Ok((archive_root, root_value))
}

fn build_archive_report(
    info_path: &Path,
    body_path: &Path,
    mdf: &MdfCliOptions,
    deep: bool,
    extract_dir: Option<&Path>,
    raw_slices: bool,
    named_entries: bool,
    indexed_entries: bool,
    strict: bool,
) -> Result<ArchiveReport> {
    let (archive_root, _) = read_archive_root(info_path, mdf)?;
    let suffix = archive_root
        .expire_suffix_list
        .first()
        .cloned()
        .unwrap_or_default();
    let entries = archive_entries(&archive_root, &suffix)?;
    let body_size = body_path
        .metadata()
        .with_context(|| format!("failed to stat {}", body_path.display()))?
        .len();

    if let Some(dir) = extract_dir {
        if indexed_entries {
            fs::create_dir_all(dir.join("entries"))
                .with_context(|| format!("failed to create {}", dir.join("entries").display()))?;
        }
        if raw_slices {
            fs::create_dir_all(dir.join("raw_slices")).with_context(|| {
                format!("failed to create {}", dir.join("raw_slices").display())
            })?;
        }
    }

    let mut reports = Vec::with_capacity(entries.len());
    let mut errors = Vec::new();
    let mut expected_offset = 0u64;

    for entry in entries {
        if entry.offset != expected_offset {
            errors.push(format!(
                "gap_or_overlap before {}: expected offset {}, got {}",
                entry.name, expected_offset, entry.offset
            ));
        }
        if entry.offset.saturating_add(entry.length) > body_size {
            errors.push(format!(
                "{} extends beyond body: offset {} + length {} > {}",
                entry.name, entry.offset, entry.length, body_size
            ));
        }

        let mut report = ArchiveEntryReport {
            index: entry.index,
            name: entry.name.clone(),
            seed_name: entry.seed_name.clone(),
            offset: entry.offset,
            length: entry.length,
            kind: ArchiveSliceKind::Raw,
            mdf_original_size: None,
            decoded_size: None,
            psb_signature_ok: None,
            output: None,
            named_output: None,
            raw_output: None,
            error: None,
        };

        let result = process_archive_entry(
            body_path,
            &entry,
            mdf,
            deep,
            extract_dir,
            raw_slices,
            named_entries,
            indexed_entries,
            &mut report,
        );
        if let Err(err) = result {
            let message = err.to_string();
            if strict {
                return Err(err).with_context(|| {
                    format!("failed to process archive entry {}", entry.name)
                });
            }
            errors.push(format!("{}: {}", entry.name, message));
            report.error = Some(message);
        }

        expected_offset = entry.offset.saturating_add(entry.length);
        reports.push(report);
    }

    if expected_offset != body_size {
        errors.push(format!(
            "body tail mismatch: last entry ends at {}, body size is {}",
            expected_offset, body_size
        ));
    }

    Ok(ArchiveReport {
        info: info_path.to_path_buf(),
        body: body_path.to_path_buf(),
        suffix,
        body_size,
        entry_count: reports.len(),
        entries: reports,
        errors,
    })
}

fn archive_entries(root: &ArchiveInfoRoot, suffix: &str) -> Result<Vec<ArchiveEntry>> {
    let mut entries = Vec::with_capacity(root.file_info.len());

    for (name, pair) in &root.file_info {
        if pair.len() < 2 {
            bail!(
                "file_info entry {} has {} values, expected at least 2",
                name,
                pair.len()
            );
        }
        entries.push(ArchiveEntry {
            index: 0,
            name: name.clone(),
            offset: pair[0],
            length: pair[1],
            seed_name: archive_entry_seed_name(name, suffix),
        });
    }

    entries.sort_by_key(|entry| entry.offset);
    for (idx, entry) in entries.iter_mut().enumerate() {
        entry.index = idx;
    }

    Ok(entries)
}

fn process_archive_entry(
    body_path: &Path,
    entry: &ArchiveEntry,
    mdf: &MdfCliOptions,
    deep: bool,
    extract_dir: Option<&Path>,
    raw_slices: bool,
    named_entries: bool,
    indexed_entries: bool,
    report: &mut ArchiveEntryReport,
) -> Result<()> {
    let slice = read_body_slice(body_path, entry.offset, entry.length)?;
    report.kind = detect_slice_kind(&slice);
    report.mdf_original_size = mdf_original_size(&slice);

    if let Some(dir) = extract_dir {
        if raw_slices {
            let raw_rel = PathBuf::from("raw_slices").join(format!(
                "{idx:04}_{name}.slice",
                idx = entry.index,
                name = sanitize_file_name(&entry.name)
            ));
            fs::write(dir.join(&raw_rel), &slice)
                .with_context(|| format!("failed to write {}", dir.join(&raw_rel).display()))?;
            report.raw_output = Some(raw_rel);
        }
    }

    let decoded = match report.kind {
        ArchiveSliceKind::Mdf if deep || extract_dir.is_some() => {
            let decoded = decode_mdf_slice_to_vec(&slice, &entry.seed_name, mdf)?;
            report.decoded_size = Some(decoded.len());
            report.psb_signature_ok = Some(has_psb_signature(&decoded));
            Some(decoded)
        }
        ArchiveSliceKind::Psb if extract_dir.is_some() => {
            report.decoded_size = Some(slice.len());
            report.psb_signature_ok = Some(true);
            Some(slice)
        }
        ArchiveSliceKind::Psb => {
            report.decoded_size = Some(slice.len());
            report.psb_signature_ok = Some(true);
            None
        }
        _ => None,
    };

    if let (Some(dir), Some(bytes)) = (extract_dir, decoded) {
        if indexed_entries {
            let ext = if has_psb_signature(&bytes) { "psb" } else { "bin" };
            let rel = PathBuf::from("entries").join(format!(
                "{idx:04}_{name}.{ext}",
                idx = entry.index,
                name = sanitize_file_name(&entry.name),
                ext = ext
            ));
            fs::write(dir.join(&rel), &bytes)
                .with_context(|| format!("failed to write {}", dir.join(&rel).display()))?;
            report.output = Some(rel);
        }

        if named_entries {
            let named_rel = editable_archive_entry_path(entry);
            let named_path = dir.join(&named_rel);
            if let Some(parent) = named_path.parent() {
                fs::create_dir_all(parent)
                    .with_context(|| format!("failed to create {}", parent.display()))?;
            }
            fs::write(&named_path, &bytes)
                .with_context(|| format!("failed to write {}", named_path.display()))?;
            report.named_output = Some(named_rel);
        }
    }

    Ok(())
}

fn pack_archive_replacement(
    path: &Path,
    original_slice: &[u8],
    original_kind: ArchiveSliceKind,
    entry: &ArchiveEntry,
    mdf: &MdfCliOptions,
    level: u8,
    body_mdf_shell: MdfWriteShell,
    seed_variant: MtSeedVariantCli,
    key_variant: MtKeyVariantCli,
) -> Result<Vec<u8>> {
    let bytes = fs::read(path).with_context(|| format!("failed to read {}", path.display()))?;

    if is_raw_slice_path(path) {
        return Ok(bytes);
    }

    match original_kind {
        ArchiveSliceKind::Mdf => {
            let shell = resolve_mdf_write_shell(body_mdf_shell, Some(MdfShell::Mt19937), mdf);
            match shell {
                MdfWriteShell::Plain => encode_plain_mdf_to_vec(&bytes, level),
                MdfWriteShell::Mt19937 => encode_mt19937_mdf_to_vec(
                    &bytes,
                    mdf,
                    &entry.seed_name,
                    level,
                    seed_variant,
                    key_variant,
                ),
                MdfWriteShell::Auto => unreachable!("resolve_mdf_write_shell never returns Auto"),
            }
        }
        ArchiveSliceKind::Psb | ArchiveSliceKind::Psz | ArchiveSliceKind::Raw => {
            if detect_slice_kind(original_slice) == ArchiveSliceKind::Mdf {
                encode_plain_mdf_to_vec(&bytes, level)
            } else {
                Ok(bytes)
            }
        }
    }
}

fn find_archive_replacement(
    in_dir: &Path,
    entry: &ArchiveEntry,
    prefer_raw_slices: bool,
) -> Option<PathBuf> {
    let safe = sanitize_file_name(&entry.name);
    let numbered = format!("{idx:04}_{safe}", idx = entry.index, safe = safe);
    let mut candidates = Vec::new();

    if prefer_raw_slices {
        candidates.push(in_dir.join("raw_slices").join(format!("{numbered}.slice")));
    }

    let editable_rel = editable_archive_entry_path(entry);
    let editable_name = editable_archive_entry_name(entry);
    candidates.extend([
        in_dir.join(&editable_rel),
        in_dir.join(&editable_name),
        in_dir.join("named_entries").join(&editable_rel),
        in_dir.join("named_entries").join(&entry.seed_name),
        in_dir.join("entries").join(format!("{numbered}.psb")),
        in_dir.join("entries").join(format!("{numbered}.bin")),
        in_dir.join(&entry.name),
        in_dir.join(&entry.seed_name),
        in_dir.join(format!("{}.psb", entry.name)),
        in_dir.join(format!("{}.bin", entry.name)),
        in_dir.join(format!("{}.json", entry.name)),
    ]);

    if !prefer_raw_slices {
        candidates.push(in_dir.join("raw_slices").join(format!("{numbered}.slice")));
    }

    candidates.into_iter().find(|path| path.is_file())
}

fn is_raw_slice_path(path: &Path) -> bool {
    path.extension()
        .and_then(|ext| ext.to_str())
        .map(|ext| ext.eq_ignore_ascii_case("slice"))
        .unwrap_or(false)
}

fn read_body_slice(path: &Path, offset: u64, length: u64) -> Result<Vec<u8>> {
    let length_usize = usize::try_from(length).context("body slice length does not fit in usize")?;
    let mut file = File::open(path).with_context(|| format!("failed to open {}", path.display()))?;
    file.seek(SeekFrom::Start(offset))
        .with_context(|| format!("failed to seek {} to {}", path.display(), offset))?;
    let mut buf = vec![0u8; length_usize];
    file.read_exact(&mut buf)
        .with_context(|| format!("failed to read {} bytes at offset {}", length, offset))?;
    Ok(buf)
}

fn decode_mdf_slice_to_vec(slice: &[u8], seed_name: &str, mdf: &MdfCliOptions) -> Result<Vec<u8>> {
    let key = require_mdf_key(mdf)?;
    let reader = BufReader::new(Cursor::new(slice.to_vec()));
    let mut mdf_reader = MdfReader::open_with_key(reader, key, seed_name, mdf.key_len)
        .with_context(|| format!("failed to open MDF slice with seed name {}", seed_name))?;
    let mut decoded = Vec::new();
    mdf_reader
        .read_to_end(&mut decoded)
        .with_context(|| format!("failed to decompress MDF slice with seed name {}", seed_name))?;
    Ok(decoded)
}

fn archive_entry_seed_name(name: &str, suffix: &str) -> String {
    if name.to_ascii_lowercase().ends_with(".m") {
        name.to_string()
    } else {
        format!("{name}{suffix}")
    }
}

fn editable_archive_entry_name(entry: &ArchiveEntry) -> String {
    editable_name_from_seed_name(&entry.seed_name)
}

fn editable_archive_entry_path(entry: &ArchiveEntry) -> PathBuf {
    safe_relative_archive_path(&editable_archive_entry_name(entry))
}

fn editable_name_from_seed_name(seed_name: &str) -> String {
    seed_name
        .strip_suffix(".m")
        .unwrap_or(seed_name)
        .to_string()
}

fn safe_relative_archive_path(name: &str) -> PathBuf {
    let normalized = name.replace('\\', "/");
    let mut path = PathBuf::new();

    for part in normalized.split('/') {
        if part.is_empty() || part == "." {
            continue;
        }
        if part == ".." {
            path.push("_");
        } else {
            path.push(sanitize_file_name(part));
        }
    }

    if path.as_os_str().is_empty() {
        PathBuf::from("entry")
    } else {
        path
    }
}

fn detect_slice_kind(slice: &[u8]) -> ArchiveSliceKind {
    if slice.starts_with(b"mdf\0") {
        ArchiveSliceKind::Mdf
    } else if slice.starts_with(b"PSB\0") {
        ArchiveSliceKind::Psb
    } else if slice.starts_with(b"PSZ\0") {
        ArchiveSliceKind::Psz
    } else {
        ArchiveSliceKind::Raw
    }
}

fn mdf_original_size(slice: &[u8]) -> Option<u32> {
    if slice.len() >= 8 && slice.starts_with(b"mdf\0") {
        Some(u32::from_le_bytes(slice[4..8].try_into().ok()?))
    } else {
        None
    }
}

fn has_psb_signature(bytes: &[u8]) -> bool {
    bytes.len() >= 4
        && u32::from_le_bytes(bytes[0..4].try_into().expect("slice length checked"))
            == PSB_SIGNATURE
}

fn sanitize_file_name(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for ch in name.chars() {
        let bad = matches!(ch, '/' | '\\' | ':' | '*' | '?' | '"' | '<' | '>' | '|')
            || ch.is_control();
        if bad {
            out.push('_');
        } else {
            out.push(ch);
        }
    }
    if out.is_empty() {
        "entry".to_string()
    } else {
        out
    }
}

fn require_mdf_key(mdf: &MdfCliOptions) -> Result<&str> {
    mdf.key
        .as_deref()
        .ok_or_else(|| anyhow!("archive body MDF slices require --mdf-key"))
}

fn open_as_psb_file(
    path: &Path,
    kind: FileKind,
    mdf: &MdfCliOptions,
) -> Result<PsbFile<BufReader<Cursor<Vec<u8>>>>> {
    let psb_bytes = match kind {
        FileKind::Psb => fs::read(path).with_context(|| format!("failed to read {}", path.display()))?,
        FileKind::Mdf => decode_mdf_to_vec(path, mdf)?,
    };
    ensure_psb_signature(&psb_bytes)
        .with_context(|| format!("{} did not decode to PSB", path.display()))?;
    let cursor = Cursor::new(psb_bytes);
    PsbFile::open(BufReader::new(cursor)).context("failed to open PSB")
}

fn open_mdf_reader<R>(
    reader: R,
    path: &Path,
    options: &MdfCliOptions,
) -> std::result::Result<MdfReader, emote_psb::mdf::error::MdfOpenError>
where
    R: BufRead,
{
    if let Some(seed) = &options.seed {
        return MdfReader::open_with_seed(reader, seed.as_bytes(), options.key_len);
    }

    if let Some(key) = &options.key {
        let file_name = options
            .name
            .as_deref()
            .or_else(|| path.file_name().and_then(|name| name.to_str()))
            .unwrap_or_default();
        return MdfReader::open_with_key(reader, key.as_str(), file_name, options.key_len);
    }

    MdfReader::open(reader)
}

fn decode_mdf_to_vec(path: &Path, mdf_options: &MdfCliOptions) -> Result<Vec<u8>> {
    let (decoded, _) = decode_mdf_to_vec_with_shell(path, mdf_options)?;
    ensure_psb_signature(&decoded)?;
    Ok(decoded)
}

fn decode_mdf_to_vec_with_shell(
    path: &Path,
    mdf_options: &MdfCliOptions,
) -> Result<(Vec<u8>, MdfShell)> {
    let file = File::open(path).with_context(|| format!("failed to open {}", path.display()))?;
    let reader = BufReader::new(file);
    let mut mdf = open_mdf_reader(reader, path, mdf_options).context("failed to open MDF")?;
    let shell = mdf.shell();
    let mut decoded = Vec::new();
    mdf.read_to_end(&mut decoded)
        .context("failed to decompress MDF")?;
    Ok((decoded, shell))
}

fn write_psb_file(
    output: &Path,
    version: u16,
    encrypted: bool,
    root: &PsbValue,
    resources: &[Vec<u8>],
    extras: &[Vec<u8>],
) -> Result<()> {
    if !extras.is_empty() && version <= 3 {
        bail!("extra resources require PSB version 4; got version {version}");
    }

    let file = File::create(output).with_context(|| format!("failed to create {}", output.display()))?;
    let stream = BufWriter::new(file);
    let mut writer = PsbWriter::new(version, encrypted, root, stream)
        .context("failed to initialize PSB writer")?;

    for (idx, bytes) in resources.iter().enumerate() {
        writer
            .add_resource(Cursor::new(bytes.clone()))
            .with_context(|| format!("failed to add resource {idx}"))?;
    }

    for (idx, bytes) in extras.iter().enumerate() {
        writer
            .add_extra(Cursor::new(bytes.clone()))
            .with_context(|| format!("failed to add extra resource {idx}"))?;
    }

    writer.finish().context("failed to write PSB")?;
    Ok(())
}

fn build_psb_vec(
    version: u16,
    encrypted: bool,
    root: &PsbValue,
    resources: &[Vec<u8>],
    extras: &[Vec<u8>],
) -> Result<Vec<u8>> {
    if !extras.is_empty() && version <= 3 {
        bail!("extra resources require PSB version 4; got version {version}");
    }

    let mut out = Vec::new();
    {
        let cursor = Cursor::new(&mut out);
        let mut writer = PsbWriter::new(version, encrypted, root, cursor)
            .context("failed to initialize PSB writer")?;

        for (idx, bytes) in resources.iter().enumerate() {
            writer
                .add_resource(Cursor::new(bytes.clone()))
                .with_context(|| format!("failed to add resource {idx}"))?;
        }

        for (idx, bytes) in extras.iter().enumerate() {
            writer
                .add_extra(Cursor::new(bytes.clone()))
                .with_context(|| format!("failed to add extra resource {idx}"))?;
        }

        writer.finish().context("failed to write PSB")?;
    }

    Ok(out)
}

fn write_mdf_file(output: &Path, psb_bytes: &[u8], level: u32) -> Result<()> {
    let level = validate_compression_level(level)?;
    let file = File::create(output).with_context(|| format!("failed to create {}", output.display()))?;
    let stream = BufWriter::new(file);
    let mut writer = MdfWriter::new(stream, level).context("failed to initialize MDF writer")?;
    writer.write_all(psb_bytes).context("failed to write MDF")?;
    let mut stream = writer.finish().context("failed to finish MDF")?;
    stream.flush().context("failed to flush MDF output")?;
    Ok(())
}

#[allow(clippy::too_many_arguments)]
fn write_archive_info_output(
    output: &Path,
    format: OutputFormat,
    version: u16,
    encrypted: bool,
    root: &PsbValue,
    level: u8,
    mdf: &MdfCliOptions,
    source_info_shell: Option<MdfShell>,
    requested_shell: MdfWriteShell,
    seed_variant: MtSeedVariantCli,
    key_variant: MtKeyVariantCli,
    info_mdf_name: Option<&str>,
) -> Result<()> {
    let kind = resolve_output_kind(output, format)?;
    match kind {
        FileKind::Psb => write_psb_file(output, version, encrypted, root, &[], &[]),
        FileKind::Mdf => {
            let psb_bytes = build_psb_vec(version, encrypted, root, &[], &[])?;
            let shell = resolve_mdf_write_shell(requested_shell, source_info_shell, mdf);
            let bytes = match shell {
                MdfWriteShell::Plain => encode_plain_mdf_to_vec(&psb_bytes, level)?,
                MdfWriteShell::Mt19937 => {
                    let seed_name = info_mdf_name
                        .map(ToOwned::to_owned)
                        .or_else(|| output.file_name().and_then(|name| name.to_str()).map(ToOwned::to_owned))
                        .ok_or_else(|| anyhow!("cannot derive output info MDF seed name"))?;
                    encode_mt19937_mdf_to_vec(
                        &psb_bytes,
                        mdf,
                        &seed_name,
                        level,
                        seed_variant,
                        key_variant,
                    )?
                }
                MdfWriteShell::Auto => unreachable!("resolve_mdf_write_shell never returns Auto"),
            };
            fs::write(output, bytes)
                .with_context(|| format!("failed to write {}", output.display()))
        }
    }
}

fn resolve_mdf_write_shell(
    requested: MdfWriteShell,
    source_shell: Option<MdfShell>,
    mdf: &MdfCliOptions,
) -> MdfWriteShell {
    match requested {
        MdfWriteShell::Plain | MdfWriteShell::Mt19937 => requested,
        MdfWriteShell::Auto => match source_shell {
            Some(MdfShell::Mt19937) if mdf.key.is_some() || mdf.seed.is_some() => MdfWriteShell::Mt19937,
            _ => MdfWriteShell::Plain,
        },
    }
}

fn encode_plain_mdf_to_vec(bytes: &[u8], level: u8) -> Result<Vec<u8>> {
    let cursor = Cursor::new(Vec::new());
    let mut writer = MdfWriter::new(cursor, level).context("failed to initialize MDF writer")?;
    writer.write_all(bytes).context("failed to write MDF payload")?;
    let cursor = writer.finish().context("failed to finish MDF payload")?;
    Ok(cursor.into_inner())
}

fn encode_mt19937_mdf_to_vec(
    bytes: &[u8],
    mdf: &MdfCliOptions,
    seed_name: &str,
    level: u8,
    seed_variant: MtSeedVariantCli,
    key_variant: MtKeyVariantCli,
) -> Result<Vec<u8>> {
    let seed = resolve_output_seed(mdf, seed_name)?;
    let key_len = if mdf.key_len == 0 {
        bail!("invalid MDF MT19937 key length 0")
    } else {
        mdf.key_len
    };

    let mut zlib_payload = Vec::new();
    {
        let mut encoder = ZlibEncoder::new(&mut zlib_payload, Compression::new(level as u32));
        encoder
            .write_all(bytes)
            .context("failed to zlib-compress MDF payload")?;
        encoder.finish().context("failed to finish zlib payload")?;
    }

    let encrypted = mt19937_xor(
        &zlib_payload,
        seed.as_bytes(),
        key_len,
        seed_variant.into(),
        key_variant.into(),
    );

    let original_len = u32::try_from(bytes.len()).context("MDF original length exceeds u32")?;
    let mut out = Vec::with_capacity(8 + encrypted.len());
    out.write_u32::<LittleEndian>(PSB_MDF_SIGNATURE)?;
    out.write_u32::<LittleEndian>(original_len)?;
    out.extend_from_slice(&encrypted);
    Ok(out)
}

fn resolve_output_seed(mdf: &MdfCliOptions, seed_name: &str) -> Result<String> {
    if let Some(seed) = &mdf.seed {
        Ok(seed.clone())
    } else if let Some(key) = &mdf.key {
        Ok(format!("{key}{seed_name}"))
    } else {
        bail!("MT19937 MDF output requires --mdf-key or --mdf-seed")
    }
}

fn read_all_normal_resource_sizes<S>(psb: &mut PsbFile<S>) -> Result<Vec<usize>>
where
    S: BufRead + Read + Seek,
{
    Ok(read_all_normal_resources(psb)?
        .into_iter()
        .map(|bytes| bytes.len())
        .collect())
}

fn read_all_extra_resource_sizes<S>(psb: &mut PsbFile<S>) -> Result<Vec<usize>>
where
    S: BufRead + Read + Seek,
{
    Ok(read_all_extra_resources(psb)?
        .into_iter()
        .map(|bytes| bytes.len())
        .collect())
}

fn read_all_normal_resources<S>(psb: &mut PsbFile<S>) -> Result<Vec<Vec<u8>>>
where
    S: BufRead + Read + Seek,
{
    let count = psb.resources();
    let mut out = Vec::with_capacity(count);
    for idx in 0..count {
        let mut resource = psb
            .open_resource(idx)
            .with_context(|| format!("failed to open resource {idx}"))?
            .ok_or_else(|| anyhow!("resource {idx} is out of range"))?;
        let mut bytes = Vec::new();
        resource
            .read_to_end(&mut bytes)
            .with_context(|| format!("failed to read resource {idx}"))?;
        out.push(bytes);
    }
    Ok(out)
}

fn read_all_extra_resources<S>(psb: &mut PsbFile<S>) -> Result<Vec<Vec<u8>>>
where
    S: BufRead + Read + Seek,
{
    let count = psb.extra_resources();
    let mut out = Vec::with_capacity(count);
    for idx in 0..count {
        let mut resource = psb
            .open_extra_resource(idx)
            .with_context(|| format!("failed to open extra resource {idx}"))?
            .ok_or_else(|| anyhow!("extra resource {idx} is out of range"))?;
        let mut bytes = Vec::new();
        resource
            .read_to_end(&mut bytes)
            .with_context(|| format!("failed to read extra resource {idx}"))?;
        out.push(bytes);
    }
    Ok(out)
}

fn read_root_json(path: &Path) -> Result<PsbValue> {
    read_json_file(path).with_context(|| format!("failed to read root JSON {}", path.display()))
}

fn read_json_file<T>(path: &Path) -> Result<T>
where
    T: for<'de> Deserialize<'de>,
{
    let file = File::open(path).with_context(|| format!("failed to open {}", path.display()))?;
    serde_json::from_reader(BufReader::new(file)).context("failed to parse JSON")
}

fn read_blobs(paths: &[PathBuf]) -> Result<Vec<Vec<u8>>> {
    paths
        .iter()
        .map(|path| fs::read(path).with_context(|| format!("failed to read {}", path.display())))
        .collect()
}

fn prepare_output_dir(path: &Path, overwrite: bool) -> Result<()> {
    if path.exists() {
        if !path.is_dir() {
            bail!("{} exists and is not a directory", path.display());
        }
        if overwrite {
            fs::remove_dir_all(path).with_context(|| format!("failed to clear {}", path.display()))?;
            fs::create_dir_all(path)
                .with_context(|| format!("failed to recreate {}", path.display()))?;
        } else if path.read_dir()?.next().is_some() {
            bail!(
                "{} is not empty; pass --overwrite to replace it",
                path.display()
            );
        }
    } else {
        fs::create_dir_all(path).with_context(|| format!("failed to create {}", path.display()))?;
    }
    Ok(())
}

fn write_json_output<T>(value: &T, output: Option<&Path>, pretty: bool) -> Result<()>
where
    T: Serialize,
{
    match output {
        Some(path) => {
            let file = File::create(path)
                .with_context(|| format!("failed to create {}", path.display()))?;
            let mut writer = BufWriter::new(file);
            if pretty {
                serde_json::to_writer_pretty(&mut writer, value).context("failed to write JSON")?;
            } else {
                serde_json::to_writer(&mut writer, value).context("failed to write JSON")?;
            }
            writer.write_all(b"\n")?;
            writer.flush()?;
        }
        None => write_json_stdout(value, pretty)?,
    }
    Ok(())
}

fn write_json_stdout<T>(value: &T, pretty: bool) -> Result<()>
where
    T: Serialize,
{
    let stdout = io::stdout();
    let mut lock = stdout.lock();
    if pretty {
        serde_json::to_writer_pretty(&mut lock, value).context("failed to write JSON")?;
    } else {
        serde_json::to_writer(&mut lock, value).context("failed to write JSON")?;
    }
    lock.write_all(b"\n")?;
    lock.flush()?;
    Ok(())
}

fn validate_compression_level(level: u32) -> Result<u8> {
    if level <= 9 {
        Ok(level as u8)
    } else {
        bail!("invalid MDF compression level {level}; valid values are 0 through 9")
    }
}

fn validate_version(version: u16) -> Result<u16> {
    match version {
        2 | 3 | 4 => Ok(version),
        _ => bail!("unsupported PSB version {version}; valid values are 2, 3, and 4"),
    }
}

fn resolve_input_kind(path: &Path, requested: InputFormat) -> Result<FileKind> {
    match requested {
        InputFormat::Psb => Ok(FileKind::Psb),
        InputFormat::Mdf => Ok(FileKind::Mdf),
        InputFormat::Auto => detect_file_kind(path),
    }
}

fn resolve_output_kind(path: &Path, requested: OutputFormat) -> Result<FileKind> {
    match requested {
        OutputFormat::Psb => Ok(FileKind::Psb),
        OutputFormat::Mdf => Ok(FileKind::Mdf),
        OutputFormat::Auto => {
            let lower = path.to_string_lossy().to_ascii_lowercase();
            if lower.ends_with(".psb.m") || lower.ends_with(".m") || lower.ends_with(".mdf") {
                Ok(FileKind::Mdf)
            } else {
                match path
                    .extension()
                    .and_then(|ext| ext.to_str())
                    .map(|ext| ext.to_ascii_lowercase())
                    .as_deref()
                {
                    Some("psb") | Some("scn") => Ok(FileKind::Psb),
                    _ => Err(anyhow!(
                        "cannot infer output format from {}; pass an explicit format",
                        path.display()
                    )),
                }
            }
        }
    }
}

fn detect_file_kind(path: &Path) -> Result<FileKind> {
    let mut file = File::open(path).with_context(|| format!("failed to open {}", path.display()))?;
    let mut sig = [0u8; 4];
    file.read_exact(&mut sig)
        .with_context(|| format!("failed to read signature from {}", path.display()))?;
    let sig = u32::from_le_bytes(sig);

    match sig {
        PSB_SIGNATURE => Ok(FileKind::Psb),
        PSB_MDF_SIGNATURE => Ok(FileKind::Mdf),
        _ => bail!(
            "{} is neither PSB nor MDF; pass --format explicitly only if you know it is valid",
            path.display()
        ),
    }
}

fn ensure_psb_signature(bytes: &[u8]) -> Result<()> {
    if bytes.len() < 4 {
        bail!("buffer is too small to contain a PSB signature");
    }
    let sig = u32::from_le_bytes(bytes[0..4].try_into().expect("slice length checked"));
    if sig == PSB_SIGNATURE {
        Ok(())
    } else {
        bail!("invalid PSB signature 0x{sig:08x}")
    }
}

#[derive(Clone, Copy)]
enum MtSeedVariant {
    Md5ArrayLe,
    Md5ArrayBe,
    Md5FirstLe,
    Md5FirstBe,
}

#[derive(Clone, Copy)]
enum MtKeyVariant {
    CyclicLeWords,
    CyclicBeWords,
    StreamLeWords,
    StreamBeWords,
}

impl From<MtSeedVariantCli> for MtSeedVariant {
    fn from(value: MtSeedVariantCli) -> Self {
        match value {
            MtSeedVariantCli::Md5ArrayLe => Self::Md5ArrayLe,
            MtSeedVariantCli::Md5ArrayBe => Self::Md5ArrayBe,
            MtSeedVariantCli::Md5FirstLe => Self::Md5FirstLe,
            MtSeedVariantCli::Md5FirstBe => Self::Md5FirstBe,
        }
    }
}

impl From<MtKeyVariantCli> for MtKeyVariant {
    fn from(value: MtKeyVariantCli) -> Self {
        match value {
            MtKeyVariantCli::CyclicLeWords => Self::CyclicLeWords,
            MtKeyVariantCli::CyclicBeWords => Self::CyclicBeWords,
            MtKeyVariantCli::StreamLeWords => Self::StreamLeWords,
            MtKeyVariantCli::StreamBeWords => Self::StreamBeWords,
        }
    }
}

fn mt19937_xor(
    payload: &[u8],
    seed: &[u8],
    key_len: usize,
    seed_variant: MtSeedVariant,
    key_variant: MtKeyVariant,
) -> Vec<u8> {
    let digest = md5(seed);
    let mut mt = match seed_variant {
        MtSeedVariant::Md5ArrayLe => {
            let keys = [
                u32::from_le_bytes(digest[0..4].try_into().expect("slice length")),
                u32::from_le_bytes(digest[4..8].try_into().expect("slice length")),
                u32::from_le_bytes(digest[8..12].try_into().expect("slice length")),
                u32::from_le_bytes(digest[12..16].try_into().expect("slice length")),
            ];
            Mt19937::from_key_array(&keys)
        }
        MtSeedVariant::Md5ArrayBe => {
            let keys = [
                u32::from_be_bytes(digest[0..4].try_into().expect("slice length")),
                u32::from_be_bytes(digest[4..8].try_into().expect("slice length")),
                u32::from_be_bytes(digest[8..12].try_into().expect("slice length")),
                u32::from_be_bytes(digest[12..16].try_into().expect("slice length")),
            ];
            Mt19937::from_key_array(&keys)
        }
        MtSeedVariant::Md5FirstLe => Mt19937::new(u32::from_le_bytes(
            digest[0..4].try_into().expect("slice length"),
        )),
        MtSeedVariant::Md5FirstBe => Mt19937::new(u32::from_be_bytes(
            digest[0..4].try_into().expect("slice length"),
        )),
    };

    match key_variant {
        MtKeyVariant::CyclicLeWords => xor_with_cyclic_key(payload, key_len, &mut mt, true),
        MtKeyVariant::CyclicBeWords => xor_with_cyclic_key(payload, key_len, &mut mt, false),
        MtKeyVariant::StreamLeWords => xor_with_stream(payload, &mut mt, true),
        MtKeyVariant::StreamBeWords => xor_with_stream(payload, &mut mt, false),
    }
}

fn xor_with_cyclic_key(
    payload: &[u8],
    key_len: usize,
    mt: &mut Mt19937,
    little_endian: bool,
) -> Vec<u8> {
    let mut key = Vec::with_capacity(key_len);
    while key.len() < key_len {
        let n = mt.next_u32();
        let bytes = if little_endian {
            n.to_le_bytes()
        } else {
            n.to_be_bytes()
        };
        key.extend_from_slice(&bytes);
    }
    key.truncate(key_len);

    payload
        .iter()
        .enumerate()
        .map(|(idx, byte)| byte ^ key[idx % key.len()])
        .collect()
}

fn xor_with_stream(payload: &[u8], mt: &mut Mt19937, little_endian: bool) -> Vec<u8> {
    let mut out = Vec::with_capacity(payload.len());
    let mut key = [0u8; 4];
    let mut key_idx = 4;

    for byte in payload {
        if key_idx >= 4 {
            let n = mt.next_u32();
            key = if little_endian {
                n.to_le_bytes()
            } else {
                n.to_be_bytes()
            };
            key_idx = 0;
        }
        out.push(byte ^ key[key_idx]);
        key_idx += 1;
    }

    out
}

struct Mt19937 {
    mt: [u32; 624],
    index: usize,
}

impl Mt19937 {
    fn new(seed: u32) -> Self {
        let mut mt = [0u32; 624];
        mt[0] = seed;
        for i in 1..624 {
            mt[i] = 1_812_433_253u32
                .wrapping_mul(mt[i - 1] ^ (mt[i - 1] >> 30))
                .wrapping_add(i as u32);
        }
        Self { mt, index: 624 }
    }

    fn from_key_array(key: &[u32]) -> Self {
        let mut rng = Self::new(19_650_218);
        let mut i = 1usize;
        let mut j = 0usize;
        let mut k = 624usize.max(key.len());
        while k > 0 {
            rng.mt[i] = (rng.mt[i]
                ^ ((rng.mt[i - 1] ^ (rng.mt[i - 1] >> 30)).wrapping_mul(1_664_525)))
            .wrapping_add(key[j])
            .wrapping_add(j as u32);
            i += 1;
            j += 1;
            if i >= 624 {
                rng.mt[0] = rng.mt[623];
                i = 1;
            }
            if j >= key.len() {
                j = 0;
            }
            k -= 1;
        }

        k = 623;
        while k > 0 {
            rng.mt[i] = (rng.mt[i]
                ^ ((rng.mt[i - 1] ^ (rng.mt[i - 1] >> 30)).wrapping_mul(1_566_083_941)))
            .wrapping_sub(i as u32);
            i += 1;
            if i >= 624 {
                rng.mt[0] = rng.mt[623];
                i = 1;
            }
            k -= 1;
        }

        rng.mt[0] = 0x8000_0000;
        rng.index = 624;
        rng
    }

    fn next_u32(&mut self) -> u32 {
        const N: usize = 624;
        const M: usize = 397;
        const MATRIX_A: u32 = 0x9908_b0df;
        const UPPER_MASK: u32 = 0x8000_0000;
        const LOWER_MASK: u32 = 0x7fff_ffff;

        if self.index >= N {
            for kk in 0..(N - M) {
                let y = (self.mt[kk] & UPPER_MASK) | (self.mt[kk + 1] & LOWER_MASK);
                self.mt[kk] = self.mt[kk + M]
                    ^ (y >> 1)
                    ^ if y & 1 != 0 { MATRIX_A } else { 0 };
            }
            for kk in (N - M)..(N - 1) {
                let y = (self.mt[kk] & UPPER_MASK) | (self.mt[kk + 1] & LOWER_MASK);
                self.mt[kk] = self.mt[kk + M - N]
                    ^ (y >> 1)
                    ^ if y & 1 != 0 { MATRIX_A } else { 0 };
            }
            let y = (self.mt[N - 1] & UPPER_MASK) | (self.mt[0] & LOWER_MASK);
            self.mt[N - 1] = self.mt[M - 1]
                ^ (y >> 1)
                ^ if y & 1 != 0 { MATRIX_A } else { 0 };
            self.index = 0;
        }

        let mut y = self.mt[self.index];
        self.index += 1;
        y ^= y >> 11;
        y ^= (y << 7) & 0x9d2c_5680;
        y ^= (y << 15) & 0xefc6_0000;
        y ^= y >> 18;
        y
    }
}

fn md5(input: &[u8]) -> [u8; 16] {
    const S: [u32; 64] = [
        7, 12, 17, 22, 7, 12, 17, 22, 7, 12, 17, 22, 7, 12, 17, 22, 5, 9, 14, 20, 5,
        9, 14, 20, 5, 9, 14, 20, 5, 9, 14, 20, 4, 11, 16, 23, 4, 11, 16, 23, 4,
        11, 16, 23, 4, 11, 16, 23, 6, 10, 15, 21, 6, 10, 15, 21, 6, 10, 15, 21,
        6, 10, 15, 21,
    ];
    const K: [u32; 64] = [
        0xd76a_a478,
        0xe8c7_b756,
        0x2420_70db,
        0xc1bd_ceee,
        0xf57c_0faf,
        0x4787_c62a,
        0xa830_4613,
        0xfd46_9501,
        0x6980_98d8,
        0x8b44_f7af,
        0xffff_5bb1,
        0x895c_d7be,
        0x6b90_1122,
        0xfd98_7193,
        0xa679_438e,
        0x49b4_0821,
        0xf61e_2562,
        0xc040_b340,
        0x265e_5a51,
        0xe9b6_c7aa,
        0xd62f_105d,
        0x0244_1453,
        0xd8a1_e681,
        0xe7d3_fbc8,
        0x21e1_cde6,
        0xc337_07d6,
        0xf4d5_0d87,
        0x455a_14ed,
        0xa9e3_e905,
        0xfcef_a3f8,
        0x676f_02d9,
        0x8d2a_4c8a,
        0xfffa_3942,
        0x8771_f681,
        0x6d9d_6122,
        0xfde5_380c,
        0xa4be_ea44,
        0x4bde_cfa9,
        0xf6bb_4b60,
        0xbebf_bc70,
        0x289b_7ec6,
        0xeaa1_27fa,
        0xd4ef_3085,
        0x0488_1d05,
        0xd9d4_d039,
        0xe6db_99e5,
        0x1fa2_7cf8,
        0xc4ac_5665,
        0xf429_2244,
        0x432a_ff97,
        0xab94_23a7,
        0xfc93_a039,
        0x655b_59c3,
        0x8f0c_cc92,
        0xffef_f47d,
        0x8584_5dd1,
        0x6fa8_7e4f,
        0xfe2c_e6e0,
        0xa301_4314,
        0x4e08_11a1,
        0xf753_7e82,
        0xbd3a_f235,
        0x2ad7_d2bb,
        0xeb86_d391,
    ];

    let mut msg = input.to_vec();
    let bit_len = (msg.len() as u64) * 8;
    msg.push(0x80);
    while msg.len() % 64 != 56 {
        msg.push(0);
    }
    msg.extend_from_slice(&bit_len.to_le_bytes());

    let mut a0 = 0x6745_2301u32;
    let mut b0 = 0xefcd_ab89u32;
    let mut c0 = 0x98ba_dcfeu32;
    let mut d0 = 0x1032_5476u32;

    for chunk in msg.chunks_exact(64) {
        let mut m = [0u32; 16];
        for (i, word) in m.iter_mut().enumerate() {
            let start = i * 4;
            *word = u32::from_le_bytes(chunk[start..start + 4].try_into().expect("slice length"));
        }

        let mut a = a0;
        let mut b = b0;
        let mut c = c0;
        let mut d = d0;

        for i in 0..64 {
            let (f, g) = if i < 16 {
                ((b & c) | ((!b) & d), i)
            } else if i < 32 {
                ((d & b) | ((!d) & c), (5 * i + 1) % 16)
            } else if i < 48 {
                (b ^ c ^ d, (3 * i + 5) % 16)
            } else {
                (c ^ (b | (!d)), (7 * i) % 16)
            };

            let temp = d;
            d = c;
            c = b;
            b = b.wrapping_add(
                a.wrapping_add(f)
                    .wrapping_add(K[i])
                    .wrapping_add(m[g])
                    .rotate_left(S[i]),
            );
            a = temp;
        }

        a0 = a0.wrapping_add(a);
        b0 = b0.wrapping_add(b);
        c0 = c0.wrapping_add(c);
        d0 = d0.wrapping_add(d);
    }

    let mut out = [0u8; 16];
    out[0..4].copy_from_slice(&a0.to_le_bytes());
    out[4..8].copy_from_slice(&b0.to_le_bytes());
    out[8..12].copy_from_slice(&c0.to_le_bytes());
    out[12..16].copy_from_slice(&d0.to_le_bytes());
    out
}
